"""Thirty-two behavioral-policy, participation, equity, and governance designs."""

# ruff: noqa: E501 -- long policy statements are indivisible catalog content.

from civicdecision.deep.models import ApplicationSuite
from civicdecision.scenario_library.matrix import axis, matrix_family
from civicdecision.scenario_library.seeds import D, R, S

SUITE = ApplicationSuite.BEHAVIORAL_EQUITY
BOUNDARY = (
    "Area and administrative differences do not establish discrimination, preferences, or individual behavior.",
    "Behavioral and allocation designs require rights, accessibility, privacy, and non-coercion review.",
    "Causal, fairness, adoption, and welfare claims require direct outcomes and independent governance evidence.",
)


BEHAVIORAL_FAMILIES = (
    matrix_family(
        family_id="equity.distributional-service",
        suite=SUITE,
        title="Distributional public-service equity",
        description=(
            "Eight decisions for disparity diagnosis, need forecasting, equity portfolios, service siting, "
            "resource allocation, corrective scheduling, disruption stress, and equity evaluation."
        ),
        affected_system="cross-agency public-service access, workload, quality, and outcome distribution",
        decision_owner="chief equity officer and city performance director",
        common_source_roles=(R.DEMOGRAPHIC_CONTEXT, R.EQUITY_ATTRIBUTE, R.MUNICIPAL_DEMAND),
        common_assumptions=(
            "Need, eligibility, access, requests, service, quality, and outcomes remain separate measures.",
            "Protected and vulnerable group reporting follows privacy, legal, and small-cell safeguards.",
        ),
        transportability_risks=(
            "Rights, demographics, service rules, need measurement, geography, and reporting access differ.",
            "Administrative denominators may omit eligible or underserved populations.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "service-disparities",
                "Diagnose distributional service-access and quality disparities",
                "Which groups and areas show persistent differences after need, eligibility, access, reporting, and case mix are separated?",
                "need-adjusted public-service access and quality disparities",
                "denominator-aware multistage service disparity decomposition",
                "unexplained service-access and quality gap",
                "percentage points",
                S.POPULATION_GROUP,
                (R.OUTCOME_PANEL, R.COMMUNITY_INPUT, R.SERVICE_SCHEDULE),
                "Do not label an adjusted area difference discrimination, individual treatment, or causal inequity.",
            ),
            axis(
                D.FORECAST,
                "equitable-service-need",
                "Forecast service need and capacity by population group",
                "What group- and area-specific eligible need and service-capacity range should planning prepare for?",
                "population-specific eligible service need and capacity",
                "denominator, eligibility, season, and access-conditioned forecasting",
                "eligible need above minimum service capacity",
                "people",
                S.POPULATION_GROUP,
                (R.OPERATING_CAPACITY, R.REAL_TIME_STATE, R.OUTCOME_PANEL),
                "Do not call forecast eligible need individual demand, behavior, entitlement, or verified unmet service.",
            ),
            axis(
                D.PRIORITIZE,
                "equity-improvement-portfolio",
                "Prioritize cross-agency equity improvements",
                "Which access, language, staffing, process, facility, and accountability investments should be funded?",
                "cross-agency service-equity improvement portfolio",
                "need, rights, disparity, evidence, cost, and deliverability prioritization",
                "population-weighted verified minimum-service gap",
                "person-service units",
                S.SERVICE_AREA,
                (R.FINANCIAL_COST, R.COMMUNITY_INPUT, R.LEGAL_REGULATORY),
                "Do not report modeled gap reduction as delivered equity, legal compliance, or resident welfare.",
            ),
            axis(
                D.SITE,
                "equitable-service-network",
                "Site an equitable network of public-service access points",
                "Where should multilingual, accessible, trusted service points close verified need-adjusted access gaps?",
                "equitable public-service access locations",
                "need-, rights-, travel-, language-, and capacity-aware facility siting",
                "eligible people beyond usable qualified service access",
                "people",
                S.FACILITY,
                (R.FACILITY_INVENTORY, R.TRANSPORT_NETWORK, R.COMMUNITY_INPUT),
                "Do not call a candidate site equitable, trusted, accessible, lawful, or used.",
            ),
            axis(
                D.ALLOCATE,
                "minimum-service-capacity",
                "Allocate capacity under minimum equitable service guarantees",
                "How should staff, funds, appointments, language, and field capacity be distributed across groups and areas?",
                "cross-agency minimum-service capacity",
                "needs-based allocation with explicit equity floors and uncertainty",
                "eligible population below minimum service coverage",
                "people",
                S.POPULATION_GROUP,
                (R.OPERATING_CAPACITY, R.SERVICE_SCHEDULE, R.COMMUNITY_INPUT),
                "Do not call area-balanced request capacity demographic equity, delivered service, or improved outcomes.",
                existing_template_ref="deep.equity.area-balance.v1",
            ),
            axis(
                D.SCHEDULE,
                "equity-remediation",
                "Schedule equity remediation and service reviews",
                "When should access repairs, outreach, translation, staffing, audits, and follow-up milestones occur?",
                "cross-agency equity remediation and review schedule",
                "rights-, severity-, dependency-, capacity-, and accountability scheduling",
                "person-days below verified minimum service standards",
                "person-days",
                S.SERVICE_AREA,
                (R.SERVICE_SCHEDULE, R.LEGAL_REGULATORY, R.COMMUNITY_INPUT),
                "Do not call scheduled remediation implemented, compliant, accepted, or effective.",
            ),
            axis(
                D.STRESS_TEST,
                "equity-under-disruption",
                "Stress-test equitable service under disruption",
                "Which continuity plan preserves minimum access across outages, hazards, demand surges, and staff losses?",
                "minimum equitable service continuity under disruption",
                "group-specific access, demand, channel, facility, and workforce failure simulation",
                "scenario-weighted people below minimum service guarantees",
                "person-days",
                S.NETWORK,
                (R.CLIMATE_HAZARD, R.FACILITY_INVENTORY, R.OPERATING_CAPACITY),
                "Do not present synthetic group outcomes, service failures, or disparities as observed.",
            ),
            axis(
                D.EVALUATE,
                "equity-policy-effect",
                "Evaluate service-equity interventions",
                "Did phased access and capacity interventions reduce verified need-adjusted disparities without displacement?",
                "phased cross-agency service-equity intervention",
                "staggered service-area evaluation with need and outcome panels",
                "change in need-adjusted service access and outcome gaps",
                "percentage points",
                S.POPULATION_GROUP,
                (R.COMMUNITY_INPUT, R.LEGAL_REGULATORY, R.SERVICE_SCHEDULE),
                "Do not infer discrimination reduction, welfare, or causal equity from area-level requests alone.",
            ),
        ),
    ),
    matrix_family(
        family_id="equity.participation-communication",
        suite=SUITE,
        title="Public participation and risk communication",
        description=(
            "Eight decisions for participation-gap diagnosis, engagement forecasting, inclusion portfolios, "
            "venue siting, outreach allocation, communication schedules, misinformation stress, and evaluation."
        ),
        affected_system="public participation, multilingual communication, consultation, and feedback closure",
        decision_owner="public engagement director and risk communications lead",
        common_source_roles=(R.COMMUNITY_INPUT, R.DEMOGRAPHIC_CONTEXT, R.GEOGRAPHIC_IDENTITY),
        common_assumptions=(
            "Invitation, exposure, participation, contribution, response, decision, and trust remain distinct.",
            "Participation records preserve consent, privacy, language, accessibility, and channel provenance.",
        ),
        transportability_risks=(
            "Trust, language, civic institutions, digital access, deliberation norms, and risk salience differ.",
            "Participants are not automatically representative of affected populations.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "participation-gaps",
                "Diagnose participation, representation, and feedback gaps",
                "Which affected groups and issues are missing across invitation, access, participation, response, and closure stages?",
                "public participation and feedback-process gaps",
                "stage-specific denominator and contribution pathway diagnosis",
                "affected people without usable participation and feedback access",
                "people",
                S.POPULATION_GROUP,
                (R.EQUITY_ATTRIBUTE, R.SERVICE_SCHEDULE, R.OUTCOME_PANEL),
                "Do not label nonparticipation apathy, opposition, consent, satisfaction, or lack of concern.",
            ),
            axis(
                D.FORECAST,
                "engagement-demand",
                "Forecast participation and communication demand",
                "What issue, language, channel, time, and accessibility demand should engagement operations prepare for?",
                "public participation and risk-communication demand",
                "issue-, channel-, language-, and event-conditioned engagement forecasting",
                "affected participation demand above usable channel capacity",
                "engagements per week",
                S.POPULATION_GROUP,
                (R.OPERATING_CAPACITY, R.REAL_TIME_STATE, R.EQUITY_ATTRIBUTE),
                "Do not call forecast engagement actual participation, agreement, trust, or public sentiment.",
            ),
            axis(
                D.PRIORITIZE,
                "inclusive-engagement-portfolio",
                "Prioritize inclusive participation and communication improvements",
                "Which language, accessibility, facilitation, compensation, channel, and feedback reforms should be funded?",
                "inclusive participation and communication improvement portfolio",
                "representation, rights, usability, trust-risk, cost, and evidence prioritization",
                "affected-population participation and feedback access gap",
                "person-engagement units",
                S.SERVICE_AREA,
                (R.FINANCIAL_COST, R.EQUITY_ATTRIBUTE, R.LEGAL_REGULATORY),
                "Do not report modeled inclusion as representative participation, consent, trust, or influence.",
            ),
            axis(
                D.SITE,
                "engagement-venues",
                "Site accessible participation and communication venues",
                "Where should in-person, mobile, partner, and digital access support close verified engagement barriers?",
                "accessible participation and communication locations",
                "travel, language, accessibility, privacy, trust, and capacity-aware siting",
                "affected people beyond usable participation access",
                "people",
                S.FACILITY,
                (R.FACILITY_INVENTORY, R.TRANSPORT_NETWORK, R.EQUITY_ATTRIBUTE),
                "Do not call a candidate venue accessible, neutral, trusted, safe, or representative.",
            ),
            axis(
                D.ALLOCATE,
                "engagement-support",
                "Allocate engagement, translation, and participation support",
                "How should outreach, interpreters, accessibility support, stipends, facilitation, and response capacity be assigned?",
                "public participation and communication support resources",
                "affected-population and minimum-access allocation",
                "affected engagement needs without assigned usable support",
                "engagements",
                S.POPULATION_GROUP,
                (R.OPERATING_CAPACITY, R.EQUITY_ATTRIBUTE, R.SERVICE_SCHEDULE),
                "Do not report allocated support as participation, representation, agreement, or influence.",
            ),
            axis(
                D.SCHEDULE,
                "engagement-feedback-cycle",
                "Schedule participation, communication, and feedback closure",
                "When should notice, translation, deliberation, response, revision, decision, and follow-up occur?",
                "public participation and feedback-closure schedule",
                "notice, accessibility, dependency, deliberation, and accountability scheduling",
                "affected person-days without timely participation or response",
                "person-days",
                S.CITYWIDE,
                (R.SERVICE_SCHEDULE, R.LEGAL_REGULATORY, R.OPERATING_CAPACITY),
                "Do not call a scheduled consultation conducted, representative, considered, or closed.",
            ),
            axis(
                D.STRESS_TEST,
                "communication-failure",
                "Stress-test public communication under crisis and channel failure",
                "Which multilingual strategy preserves accurate usable communication under uncertainty, outage, rumor, and capacity loss?",
                "public risk communication under crisis and channel failure",
                "message, channel, language, trust, misinformation, and capacity simulation",
                "scenario-weighted affected people without timely usable information",
                "people",
                S.NETWORK,
                (R.REAL_TIME_STATE, R.OPERATING_CAPACITY, R.FACILITY_INVENTORY),
                "Do not present simulated message reach, understanding, trust, or behavior as observed.",
            ),
            axis(
                D.EVALUATE,
                "engagement-design-effect",
                "Evaluate inclusive engagement and risk communication",
                "Did phased language, access, deliberation, or feedback changes improve verified participation and understanding?",
                "phased inclusive engagement and communication redesign",
                "randomized encouragement or staggered process evaluation",
                "change in verified usable participation and comprehension",
                "percentage points",
                S.POPULATION_GROUP,
                (R.EQUITY_ATTRIBUTE, R.SERVICE_SCHEDULE, R.LEGAL_REGULATORY),
                "Do not infer trust, consent, legitimacy, behavior, or policy influence from attendance alone.",
            ),
        ),
    ),
    matrix_family(
        family_id="equity.compliance-incentives",
        suite=SUITE,
        title="Compliance, incentives, and behavioral policy",
        description=(
            "Eight decisions for process diagnosis, workload forecasting, policy portfolios, service siting, "
            "support allocation, contact scheduling, behavior stress, and incentive evaluation."
        ),
        affected_system="rights-preserving compliance assistance, incentives, inspections, and enforcement",
        decision_owner="regulatory operations director and behavioral insights lead",
        common_source_roles=(R.LEGAL_REGULATORY, R.MUNICIPAL_DEMAND, R.DEMOGRAPHIC_CONTEXT),
        common_assumptions=(
            "Eligibility, notice, awareness, capability, action, inspection, violation, sanction, and outcome remain distinct.",
            "No behavioral score automatically triggers enforcement, benefit denial, or coercive action.",
        ),
        transportability_risks=(
            "Law, administrative burden, trust, incentives, capability, enforcement, and baseline behavior differ.",
            "Observed compliance may reflect detection and documentation rather than underlying behavior.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "compliance-process-friction",
                "Diagnose compliance and administrative-burden pathways",
                "Which notice, eligibility, capability, process, inspection, and enforcement stages create verified friction or unequal burden?",
                "compliance assistance and administrative-burden pathways",
                "rights-aware stage and denominator process diagnosis",
                "eligible or regulated cases with unresolved process barriers",
                "cases",
                S.POPULATION_GROUP,
                (R.EQUITY_ATTRIBUTE, R.COMMUNITY_INPUT, R.OUTCOME_PANEL),
                "Do not label non-completion intentional noncompliance, irresponsibility, risk, or guilt.",
            ),
            axis(
                D.FORECAST,
                "assistance-inspection-demand",
                "Forecast compliance assistance and inspection demand",
                "What rule, group, channel, season, and deadline-specific workload should operations prepare for?",
                "compliance assistance and inspection workload",
                "deadline, policy, channel, case-mix, and season forecasting",
                "priority assistance and inspection demand above capacity",
                "cases per week",
                S.SERVICE_AREA,
                (R.OPERATING_CAPACITY, R.SERVICE_SCHEDULE, R.REAL_TIME_STATE),
                "Do not call forecast cases violations, intentional behavior, or enforcement outcomes.",
            ),
            axis(
                D.PRIORITIZE,
                "compliance-policy-portfolio",
                "Prioritize compliance assistance and policy redesign",
                "Which simplification, reminder, incentive, technical support, inspection, and accountability measures should be funded?",
                "rights-preserving compliance and assistance portfolio",
                "burden, effectiveness evidence, rights, equity, cost, and deliverability prioritization",
                "verified unresolved compliance burden and harm risk",
                "case-days",
                S.SERVICE_AREA,
                (R.FINANCIAL_COST, R.EQUITY_ATTRIBUTE, R.COMMUNITY_INPUT),
                "Do not report modeled compliance change as lawful behavior, public benefit, or welfare improvement.",
            ),
            axis(
                D.SITE,
                "compliance-assistance-access",
                "Site compliance assistance and technical-support access",
                "Where should non-enforcement assistance, document, inspection, and technical services reduce verified barriers?",
                "compliance assistance and technical-support locations",
                "access, privacy, language, neutrality, skill, and capacity-aware siting",
                "eligible cases beyond usable qualified assistance",
                "cases",
                S.FACILITY,
                (R.FACILITY_INVENTORY, R.TRANSPORT_NETWORK, R.EQUITY_ATTRIBUTE),
                "Do not call a candidate assistance site trusted, neutral, accessible, qualified, or used.",
            ),
            axis(
                D.ALLOCATE,
                "assistance-enforcement-capacity",
                "Allocate compliance assistance and inspection capacity",
                "How should navigators, technical aid, incentives, inspectors, language, and appeal support be assigned?",
                "compliance assistance, inspection, and appeal resources",
                "rights, severity, minimum-assistance, skill, and equity allocation",
                "priority cases without qualified assistance or review capacity",
                "cases",
                S.POPULATION_GROUP,
                (R.OPERATING_CAPACITY, R.EQUITY_ATTRIBUTE, R.SERVICE_SCHEDULE),
                "Do not report assigned assistance or inspection as contact, compliance, violation, sanction, or resolution.",
            ),
            axis(
                D.SCHEDULE,
                "notice-assistance-inspection",
                "Schedule notices, assistance, inspections, and appeals",
                "When should notice, support, cure periods, inspection, decision, appeal, and follow-up occur?",
                "compliance notice, assistance, inspection, and appeal schedule",
                "rights, deadline, dependency, capacity, and burden-aware scheduling",
                "case-days outside lawful notice, assistance, and review windows",
                "case-days",
                S.SERVICE_AREA,
                (R.SERVICE_SCHEDULE, R.OPERATING_CAPACITY, R.EQUITY_ATTRIBUTE),
                "Do not call scheduled notice delivered, understood, lawful, cured, inspected, or adjudicated.",
            ),
            axis(
                D.STRESS_TEST,
                "policy-response-uncertainty",
                "Stress-test behavioral policy under heterogeneous response",
                "Which assistance and incentive strategy remains rights-preserving across uptake, substitution, burden, and enforcement scenarios?",
                "behavioral compliance policy under heterogeneous response",
                "agent, administrative burden, uptake, substitution, and capacity simulation",
                "scenario-weighted unresolved harm and administrative burden",
                "case-days",
                S.POPULATION_GROUP,
                (R.EQUITY_ATTRIBUTE, R.OPERATING_CAPACITY, R.COMMUNITY_INPUT),
                "Do not present simulated preferences, responses, compliance, or welfare as observed behavior.",
            ),
            axis(
                D.EVALUATE,
                "assistance-incentive-effect",
                "Evaluate compliance assistance and incentives",
                "Did randomized or phased assistance improve verified lawful completion without burden or coercion?",
                "randomized or phased compliance assistance and incentive",
                "randomized encouragement or threshold-based policy evaluation",
                "change in verified timely lawful completion and administrative burden",
                "percentage points and minutes",
                S.POPULATION_GROUP,
                (R.EQUITY_ATTRIBUTE, R.COMMUNITY_INPUT, R.OUTCOME_PANEL),
                "Do not infer intent, welfare, deterrence, or durable behavior from one administrative completion outcome.",
            ),
        ),
    ),
    matrix_family(
        family_id="equity.algorithmic-governance",
        suite=SUITE,
        title="Algorithmic decision support and governance",
        description=(
            "Eight decisions for system diagnosis, workload forecasting, control portfolios, review siting, "
            "oversight allocation, audit scheduling, failure stress, and causal system evaluation."
        ),
        affected_system="public-sector analytical, scoring, triage, optimization, and human-review systems",
        decision_owner="algorithmic accountability officer and responsible technology review board",
        common_source_roles=(R.LEGAL_REGULATORY, R.EQUITY_ATTRIBUTE, R.OUTCOME_PANEL),
        common_assumptions=(
            "Model output, recommendation, human decision, action, appeal, service, and outcome remain distinct.",
            "High-impact decisions require lawful authority, human responsibility, contestability, and incident response.",
        ),
        transportability_risks=(
            "Law, institutional process, data-generating systems, populations, incentives, and recourse differ.",
            "Technical fairness metrics may conflict and cannot establish legal or substantive fairness alone.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "decision-system-risks",
                "Diagnose algorithmic decision-system risks and control gaps",
                "Which data, model, interface, human, action, appeal, and outcome stages have unresolved evidence or governance gaps?",
                "algorithmic decision-system evidence and control gaps",
                "end-to-end claim, lineage, decision, recourse, and outcome diagnosis",
                "high-impact decision pathways with unresolved controls",
                "pathways",
                S.NETWORK,
                (R.INTERVENTION_ASSIGNMENT, R.COMMUNITY_INPUT, R.SERVICE_SCHEDULE),
                "Do not label a metric gap unlawful discrimination or a documented control effective without evidence.",
            ),
            axis(
                D.FORECAST,
                "review-appeal-demand",
                "Forecast human review, recourse, and audit demand",
                "What decision, override, appeal, incident, drift, and audit workload should governance capacity prepare for?",
                "algorithmic decision review, appeal, and audit demand",
                "decision-volume, drift, incident, recourse, and policy-change forecasting",
                "high-impact decisions above qualified review capacity",
                "decisions per week",
                S.SERVICE_AREA,
                (R.OPERATING_CAPACITY, R.REAL_TIME_STATE, R.SERVICE_SCHEDULE),
                "Do not call forecast reviews errors, violations, harms, discrimination, or appeals filed.",
            ),
            axis(
                D.PRIORITIZE,
                "governance-controls",
                "Prioritize algorithmic governance controls",
                "Which documentation, data, evaluation, interface, human review, recourse, monitoring, and sunset controls should be funded?",
                "algorithmic governance and risk-control portfolio",
                "impact, evidence gap, rights, feasibility, dependency, and lifecycle prioritization",
                "high-impact decision volume without verified controls",
                "decisions",
                S.ASSET,
                (R.FINANCIAL_COST, R.COMMUNITY_INPUT, R.OPERATING_CAPACITY),
                "Do not report a planned control as implemented, effective, lawful, certified, or independently audited.",
            ),
            axis(
                D.SITE,
                "human-review-access",
                "Site independent review and recourse access",
                "Where should accessible human review, appeal assistance, and independent oversight be available?",
                "algorithmic decision review and recourse locations",
                "rights, privacy, language, independence, access, and capacity-aware siting",
                "affected people beyond usable independent review access",
                "people",
                S.FACILITY,
                (R.FACILITY_INVENTORY, R.TRANSPORT_NETWORK, R.COMMUNITY_INPUT),
                "Do not call a candidate review channel independent, accessible, confidential, lawful, or used.",
            ),
            axis(
                D.ALLOCATE,
                "oversight-capacity",
                "Allocate human review and oversight capacity",
                "How should reviewers, auditors, advocates, incident responders, and domain experts be assigned?",
                "algorithmic human review and oversight resources",
                "impact, rights, expertise, conflict, and minimum-review allocation",
                "high-impact decisions without qualified independent review capacity",
                "decisions",
                S.SERVICE_AREA,
                (R.OPERATING_CAPACITY, R.SERVICE_SCHEDULE, R.COMMUNITY_INPUT),
                "Do not report assigned review as completed, independent, correct, accepted, or remedied.",
            ),
            axis(
                D.SCHEDULE,
                "audit-monitoring-cycle",
                "Schedule algorithmic audit, monitoring, review, and sunset",
                "When should pre-deployment review, monitoring, drift checks, incident response, recertification, and sunset occur?",
                "algorithmic system audit and governance schedule",
                "impact, change, drift, incident, dependency, and legal-deadline scheduling",
                "high-impact system-days outside verified governance controls",
                "system-days",
                S.ASSET,
                (R.SERVICE_SCHEDULE, R.REAL_TIME_STATE, R.COMMUNITY_INPUT),
                "Do not call a scheduled audit performed, independent, passed, certified, or remediated.",
            ),
            axis(
                D.STRESS_TEST,
                "algorithmic-failure",
                "Stress-test algorithmic systems and human fallback",
                "Which controls preserve lawful service under drift, missingness, manipulation, outage, override, and demand surge?",
                "algorithmic decision support under technical and institutional failure",
                "data, model, interface, human, vendor, attack, and capacity failure simulation",
                "scenario-weighted high-impact decisions outside safe fallback",
                "decisions",
                S.NETWORK,
                (R.REAL_TIME_STATE, R.OPERATING_CAPACITY, R.COMMUNITY_INPUT),
                "Do not present synthetic failures, decisions, affected people, or harms as observed incidents.",
            ),
            axis(
                D.EVALUATE,
                "decision-support-effect",
                "Evaluate algorithmic decision support and human review",
                "Did phased decision support improve verified service outcomes without unequal error, automation bias, or reduced recourse?",
                "phased algorithmic decision-support and human-review system",
                "randomized rollout or threshold-based socio-technical evaluation",
                "change in verified service outcome, error, override, and recourse gaps",
                "percentage points",
                S.POPULATION_GROUP,
                (R.COMMUNITY_INPUT, R.SERVICE_SCHEDULE, R.OPERATING_CAPACITY),
                "Do not infer causal service effectiveness from aggregate before-after counts without assignment and counterfactual evidence.",
                existing_template_ref="deep.equity.causal-service-effectiveness.v1",
            ),
        ),
    ),
)

__all__ = ["BEHAVIORAL_FAMILIES"]
