"""Forty climate and disaster-resilience decision designs."""

# ruff: noqa: E501 -- long policy statements are indivisible catalog content.

from civicdecision.deep.models import ApplicationSuite
from civicdecision.scenario_library.seeds import C, D, FamilySeed, G, H, M, R, S, seed

SUITE = ApplicationSuite.CLIMATE_DISASTER
CLIMATE_BOUNDARY = (
    "Hazard observations and modeled exposure do not establish individual harm or causation.",
    "Proposed adaptations are planning alternatives, not adopted policy or engineered designs.",
    "A design-only record is not a city execution, validated forecast, or impact result.",
)


CLIMATE_FAMILIES = (
    FamilySeed(
        family_id="climate.extreme-heat",
        suite=SUITE,
        title="Extreme heat exposure and response",
        description=(
            "Decision designs spanning heat-risk diagnosis, cooling access, operational response, "
            "adaptation investment, compound stress, and intervention evaluation."
        ),
        affected_system="urban heat-health and cooling-response system",
        decision_owner="chief resilience officer and public-health incident lead",
        common_source_roles=(R.CLIMATE_HAZARD, R.GEOGRAPHIC_IDENTITY, R.DEMOGRAPHIC_CONTEXT),
        common_assumptions=(
            "Heat indicators are aligned to a declared local time zone and spatial support.",
            "Cooling capacity, costs, and response effects remain explicit planning inputs.",
        ),
        transportability_risks=(
            "Building stock, acclimatization, canopy, humidity, and reporting behavior vary by city.",
            "Thresholds calibrated in one climate zone may not transfer to another.",
        ),
        claim_boundary=CLIMATE_BOUNDARY,
        designs=(
            seed(
                D.DIAGNOSE,
                "heat-access-gaps",
                "Diagnose neighborhood heat exposure and cooling-access gaps",
                "Which neighborhoods combine sustained heat exposure, vulnerable populations, and weak cooling access?",
                "neighborhood heat-exposure and cooling-access gaps",
                "spatial overlay of heat, vulnerability, canopy, and cooling access",
                "population in high-heat low-access areas",
                "people",
                C.EQUITY,
                "Risk strata must be comparable across neighborhoods without suppressing small vulnerable groups.",
                G.GEOGRAPHIC_ALIGNMENT,
                "Every hazard, population, canopy, and facility layer resolves to the same dated neighborhood geography.",
                H.SEASONAL,
                S.NEIGHBORHOOD,
                (M.DESCRIPTIVE,),
                (R.FACILITY_INVENTORY, R.ENVIRONMENTAL_EXPOSURE, R.EQUITY_ATTRIBUTE),
                "Current cooling resources and observed heat exposure remain unchanged.",
                (
                    "target mobile cooling support to high-risk low-access neighborhoods",
                    "extend hours at existing cooling facilities near identified gaps",
                    "combine canopy, shade, and household cooling assistance",
                ),
                "Do not label an exposure-access screen as observed illness or a causal vulnerability score.",
            ),
            seed(
                D.FORECAST,
                "heat-service-demand",
                "Forecast heat-triggered public-service demand",
                "What daily cooling, welfare-check, and service workload range should operations prepare for during forecast heat?",
                "daily heat-response service demand",
                "weather-conditioned hierarchical demand forecasting",
                "unserved heat-response requests",
                "requests per day",
                C.CAPACITY,
                "Forecast workload cannot exceed the declared staffing and cooling-support service envelope without escalation.",
                G.CALIBRATION,
                "Backtests meet declared interval coverage and error thresholds across both ordinary and extreme-heat days.",
                H.DAYS,
                S.SERVICE_AREA,
                (M.FORECAST,),
                (R.MUNICIPAL_DEMAND, R.OPERATING_CAPACITY),
                "Staffing follows the ordinary-season roster and facilities keep standard hours.",
                (
                    "activate a moderate heat-response staffing reserve",
                    "pre-position rotating welfare-check and cooling teams",
                    "use forecast intervals to trigger staged surge capacity",
                ),
                "Do not report forecast requests as emergency visits, deaths, or verified unmet need.",
            ),
            seed(
                D.PRIORITIZE,
                "cooling-investments",
                "Prioritize shade, cool-roof, and cooling retrofit investments",
                "Which heat-mitigation projects should enter the funded portfolio under cost, exposure, and equity constraints?",
                "heat-mitigation capital project portfolio",
                "multi-criteria ranking of shade, cool-roof, and retrofit projects",
                "residual person-days of extreme heat exposure",
                "person-days",
                C.BUDGET,
                "Selected heat-mitigation projects must fit the adopted capital and maintenance budget envelope.",
                G.COST_CAPACITY,
                "Every candidate has a dated cost, service life, deliverability estimate, and exposure-reduction basis.",
                H.MULTI_YEAR,
                S.ASSET,
                (M.DESCRIPTIVE, M.OPTIMIZATION),
                (R.ASSET_INVENTORY, R.ASSET_CONDITION, R.FINANCIAL_COST),
                "No additional heat-mitigation capital projects are funded beyond the current program.",
                (
                    "fund the highest exposure-reduction projects per dollar",
                    "reserve funding for high-vulnerability neighborhoods",
                    "balance near-term shade with longer-lived building retrofits",
                ),
                "Do not call modeled exposure reduction a measured temperature or health outcome.",
            ),
            seed(
                D.SITE,
                "cooling-center-network",
                "Site an accessible cooling-center network",
                "Where should seasonal cooling centers open to reduce travel barriers while respecting facility capacity?",
                "seasonal cooling-center locations",
                "capacitated facility-location optimization with walking and transit impedance",
                "high-risk residents beyond the cooling-access threshold",
                "people",
                C.CAPACITY,
                "Each selected facility must satisfy occupancy, backup-power, staffing, and accessible-entry capacity.",
                G.NETWORK_READINESS,
                "Versioned pedestrian and transit networks pass topology, impedance, schedule, and accessibility checks.",
                H.SEASONAL,
                S.FACILITY,
                (M.DESCRIPTIVE, M.OPTIMIZATION),
                (R.FACILITY_INVENTORY, R.TRANSPORT_NETWORK, R.OPERATING_CAPACITY),
                "Only currently designated cooling sites operate with their published capacities.",
                (
                    "open high-capacity public facilities in the largest access gaps",
                    "deploy smaller pop-up sites near transit-poor high-risk areas",
                    "combine fixed centers with accessible transport assistance",
                ),
                "Do not infer accessible cooling from straight-line distance or an unvalidated network.",
            ),
            seed(
                D.ALLOCATE,
                "heat-response-resources",
                "Allocate heat-response teams and cooling supplies",
                "How should limited outreach teams, transport slots, and cooling supplies be distributed during a heat emergency?",
                "heat-emergency outreach and cooling resources",
                "equity-constrained resource allocation across service areas",
                "high-risk residents without assigned heat-response capacity",
                "people",
                C.EQUITY,
                "No high-vulnerability service area may fall below the declared minimum response coverage.",
                G.EQUITY_MEASUREMENT,
                "Coverage denominators, vulnerability attributes, and minimum-service rules are complete and policy-approved.",
                H.DAYS,
                S.SERVICE_AREA,
                (M.SIMULATION, M.OPTIMIZATION),
                (R.OPERATING_CAPACITY, R.EQUITY_ATTRIBUTE, R.REAL_TIME_STATE),
                "Teams and supplies follow the existing equal-share distribution rule.",
                (
                    "allocate by exposed population and verified service capacity",
                    "protect minimum coverage before assigning remaining resources",
                    "reallocate daily using observed utilization and updated heat conditions",
                ),
                "Do not describe an optimized allocation as delivered services or reduced mortality.",
            ),
            seed(
                D.SCHEDULE,
                "heat-operations-calendar",
                "Schedule heat-response shifts and facility hours",
                "When should staff shifts, cooling-center hours, and welfare checks expand across a multi-day heat event?",
                "heat-response operating calendar",
                "forecast-triggered shift and facility-hour scheduling",
                "hours of forecast demand above staffed capacity",
                "service-hours",
                C.TIME,
                "Schedules must respect labor rest rules, facility opening constraints, and activation lead times.",
                G.TEMPORAL_ALIGNMENT,
                "Forecast issue times, operating calendars, labor rosters, and observations use a common timezone and cutoff.",
                H.DAYS,
                S.CITYWIDE,
                (M.FORECAST, M.OPTIMIZATION),
                (R.SERVICE_SCHEDULE, R.OPERATING_CAPACITY, R.REAL_TIME_STATE),
                "Standard summer shifts and facility hours remain in place.",
                (
                    "extend hours only on threshold heat days",
                    "stagger teams to cover overnight heat retention",
                    "use rolling forecasts to adapt shifts and center hours",
                ),
                "Do not treat a proposed roster as an implemented labor plan or verified response time.",
            ),
            seed(
                D.STRESS_TEST,
                "compound-heat-continuity",
                "Stress-test service continuity during compound heat",
                "Which continuity portfolio remains feasible under prolonged heat, power loss, and service-demand surge assumptions?",
                "compound-heat service-continuity portfolio",
                "multi-hazard Monte Carlo stress testing of facilities and response capacity",
                "scenario-weighted hours of critical service interruption",
                "service-hours",
                C.RISK,
                "Critical cooling and welfare-check functions must remain above the declared minimum continuity level.",
                G.LINEAGE,
                "Observed workload and gridded heat inputs retain source lineage while outage and intervention effects remain labeled assumptions.",
                H.WEEKS,
                S.CITYWIDE,
                (M.FORECAST, M.SIMULATION, M.OPTIMIZATION),
                (R.MUNICIPAL_DEMAND, R.OPERATING_CAPACITY),
                "Existing facilities and ordinary surge protocols face the compound event without added redundancy.",
                (
                    "pre-position backup power at the highest-load cooling sites",
                    "create redundant mobile cooling and welfare-check teams",
                    "stage capacity using conservative heat and outage scenarios",
                ),
                "Do not claim that simulated outages caused observed requests or that a stress test predicts an actual disaster.",
                existing_template_ref="deep.climate.heat-service-surge.v1",
            ),
            seed(
                D.EVALUATE,
                "cool-roof-impact",
                "Evaluate a cool-roof and household-cooling program",
                "Did the phased heat-adaptation program reduce indoor heat burden without widening service disparities?",
                "phased cool-roof and household-cooling intervention",
                "pre-registered staggered-adoption causal evaluation",
                "change in measured indoor overheating hours",
                "hours per household",
                C.EQUITY,
                "Impact estimates must report heterogeneous effects for pre-specified vulnerability groups without post-treatment selection.",
                G.IDENTIFICATION,
                "Dated assignment, untreated comparisons, pre-trends, outcome panels, attrition checks, and falsification tests satisfy the analysis plan.",
                H.MULTI_YEAR,
                S.POPULATION_GROUP,
                (M.DESCRIPTIVE, M.CAUSAL),
                (
                    R.INTERVENTION_ASSIGNMENT,
                    R.OUTCOME_PANEL,
                    R.ENVIRONMENTAL_EXPOSURE,
                    R.EQUITY_ATTRIBUTE,
                ),
                "Eligible households continue under the pre-program cooling conditions.",
                (
                    "compare phased recipients with not-yet-treated eligible households",
                    "estimate effects separately for roof and equipment interventions",
                    "evaluate combined adaptation with pre-specified equity heterogeneity",
                ),
                "Do not infer health effects from indoor temperature alone or call association causal without the identification gate.",
            ),
        ),
    ),
    FamilySeed(
        family_id="climate.flood-stormwater",
        suite=SUITE,
        title="Flood and stormwater resilience",
        description=(
            "Decision designs for drainage diagnosis, rainfall-runoff workload, green infrastructure, "
            "response deployment, maintenance timing, compound flooding, and causal evaluation."
        ),
        affected_system="urban drainage, stormwater, and flood-response system",
        decision_owner="stormwater utility director and emergency-management lead",
        common_source_roles=(R.CLIMATE_HAZARD, R.GEOGRAPHIC_IDENTITY, R.ASSET_INVENTORY),
        common_assumptions=(
            "Rainfall, terrain, drainage, and complaint records use explicit spatial and temporal supports.",
            "Hydraulic capacities and intervention effects remain measured inputs or labeled assumptions.",
        ),
        transportability_risks=(
            "Drainage standards, imperviousness, topography, tides, and maintenance regimes differ.",
            "Complaint density may reflect reporting access rather than flood incidence.",
        ),
        claim_boundary=CLIMATE_BOUNDARY,
        designs=(
            seed(
                D.DIAGNOSE,
                "drainage-failure-patterns",
                "Diagnose recurrent drainage-failure patterns",
                "Where do rainfall, drainage condition, surface flow paths, and verified flooding jointly indicate failure risk?",
                "recurrent drainage-failure locations",
                "event-linked geospatial failure-pattern diagnosis",
                "verified flood events unexplained by mapped drainage capacity",
                "events",
                C.TECHNICAL,
                "A hotspot must be supported by verified events and mapped drainage connectivity rather than complaints alone.",
                G.GEOGRAPHIC_ALIGNMENT,
                "Flood observations, rainfall cells, terrain, catchments, and drainage assets share a validated coordinate and topology model.",
                H.ANNUAL,
                S.ASSET,
                (M.DESCRIPTIVE,),
                (R.ASSET_CONDITION, R.ENVIRONMENTAL_EXPOSURE, R.MUNICIPAL_DEMAND),
                "Current drainage assets and maintenance practices continue.",
                (
                    "inspect verified recurrent failure assets",
                    "instrument uncertain high-consequence catchments",
                    "combine targeted cleaning with structural investigation",
                ),
                "Do not convert flood complaints into verified inundation depths or engineering failure diagnoses.",
            ),
            seed(
                D.FORECAST,
                "runoff-response-demand",
                "Forecast rainfall-runoff response demand",
                "What range of pumping, road-closure, and resident-assistance demand follows the forecast rainfall envelope?",
                "event-level stormwater response demand",
                "rainfall-conditioned probabilistic operations forecasting",
                "response tasks above available event capacity",
                "tasks per event",
                C.CAPACITY,
                "The forecast must distinguish routine service calls from verified emergency response tasks.",
                G.CALIBRATION,
                "Held-out storms meet declared event-total, peak-timing, and interval-coverage diagnostics.",
                H.DAYS,
                S.SERVICE_AREA,
                (M.FORECAST,),
                (R.MUNICIPAL_DEMAND, R.OPERATING_CAPACITY, R.REAL_TIME_STATE),
                "Crews and pumps follow ordinary wet-weather activation levels.",
                (
                    "activate crews from rainfall thresholds",
                    "stage pumps from forecast catchment loads",
                    "use rolling event forecasts with conservative capacity reserves",
                ),
                "Do not present forecast operational demand as predicted flood depth or property damage.",
            ),
            seed(
                D.PRIORITIZE,
                "drainage-renewal",
                "Prioritize drainage renewal and green-infrastructure projects",
                "Which asset renewals and runoff-reduction projects best reduce expected disruption under the capital ceiling?",
                "stormwater capital-renewal portfolio",
                "risk-adjusted asset and green-infrastructure portfolio optimization",
                "expected annual service-disruption hours",
                "service-hours per year",
                C.BUDGET,
                "The selected portfolio must fit capital, maintenance, land, and delivery-year budgets.",
                G.COST_CAPACITY,
                "Candidate costs, hydraulic benefits, maintenance loads, dependencies, and delivery capacity are independently reviewed.",
                H.MULTI_YEAR,
                S.ASSET,
                (M.SIMULATION, M.OPTIMIZATION),
                (R.ASSET_CONDITION, R.FINANCIAL_COST, R.OPERATING_CAPACITY),
                "Only already-funded drainage renewal proceeds.",
                (
                    "renew highest expected-loss drainage assets",
                    "fund distributed green infrastructure in overloaded catchments",
                    "optimize a mixed structural and nature-based portfolio",
                ),
                "Do not call modeled avoided disruption a realized financial saving.",
            ),
            seed(
                D.SITE,
                "retention-storage-sites",
                "Site distributed stormwater retention and storage",
                "Which parcels can host retention while reducing runoff and avoiding displacement or environmental harm?",
                "stormwater retention and temporary-storage sites",
                "parcel-constrained hydrologic facility-location analysis",
                "unmanaged design-storm runoff volume",
                "cubic meters",
                C.ENVIRONMENTAL,
                "Sites must avoid protected habitat, contaminated land, displacement risk, and infeasible subsurface conditions.",
                G.LEGAL_AUTHORITY,
                "Parcel control, permitting authority, environmental screening, and maintenance responsibility are documented.",
                H.MULTI_YEAR,
                S.PARCEL,
                (M.SIMULATION, M.OPTIMIZATION),
                (R.LAND_PARCEL, R.LEGAL_REGULATORY, R.FINANCIAL_COST),
                "No new distributed retention sites are acquired.",
                (
                    "use publicly controlled parcels in overloaded catchments",
                    "incentivize private parcels with high runoff-reduction potential",
                    "combine regional storage with distributed neighborhood retention",
                ),
                "Do not treat a screened parcel as acquired, permitted, or hydraulically designed.",
            ),
            seed(
                D.ALLOCATE,
                "flood-response-assets",
                "Allocate pumps, barriers, and flood-response crews",
                "How should mobile pumps, barriers, and response teams be assigned as observed conditions change?",
                "mobile flood-response assets",
                "rolling risk-constrained deployment optimization",
                "critical locations without timely flood-response coverage",
                "locations",
                C.TIME,
                "Travel, setup, relocation, and crew-safety times must fit the forecast lead-time window.",
                G.TEMPORAL_ALIGNMENT,
                "Sensor timestamps, weather updates, road status, asset location, and dispatch state pass freshness checks.",
                H.REAL_TIME,
                S.NETWORK,
                (M.SIMULATION, M.OPTIMIZATION),
                (R.OPERATING_CAPACITY, R.REAL_TIME_STATE, R.TRANSPORT_NETWORK),
                "Mobile assets remain at their ordinary depots until manual dispatch.",
                (
                    "pre-position from forecast catchment risk",
                    "reserve capacity for critical facilities before general deployment",
                    "reoptimize assignments as roads and water levels change",
                ),
                "Do not call a modeled dispatch plan an executed emergency response.",
            ),
            seed(
                D.SCHEDULE,
                "drainage-maintenance-window",
                "Schedule drainage inspection and maintenance windows",
                "When should catch basins, culverts, and pumps be inspected or cleared before forecast wet periods?",
                "preventive stormwater maintenance calendar",
                "weather-aware condition-based maintenance scheduling",
                "high-risk asset-days overdue before major rainfall",
                "asset-days",
                C.CAPACITY,
                "The schedule must respect crew skills, access permits, traffic windows, and equipment availability.",
                G.TEMPORAL_ALIGNMENT,
                "Condition inspections, work orders, forecast windows, and asset histories share effective dates and completion semantics.",
                H.WEEKS,
                S.ASSET,
                (M.FORECAST, M.OPTIMIZATION),
                (R.ASSET_CONDITION, R.SERVICE_SCHEDULE, R.OPERATING_CAPACITY),
                "Assets follow fixed cyclical maintenance intervals.",
                (
                    "advance overdue high-consequence assets",
                    "schedule catchment-wide cleaning before seasonal rainfall",
                    "balance condition risk with forecast-triggered maintenance windows",
                ),
                "Do not equate a service request closure with verified maintenance completion.",
            ),
            seed(
                D.STRESS_TEST,
                "compound-rainfall-continuity",
                "Stress-test continuity under compound rainfall and outage",
                "Which continuity strategy remains viable across rainfall, tide, blockage, outage, and demand-surge scenarios?",
                "compound-flood service-continuity strategy",
                "joint rainfall-tide-blockage-outage scenario simulation",
                "scenario-weighted critical service interruption",
                "service-hours",
                C.RISK,
                "Critical drainage and emergency functions must stay above the minimum continuity threshold in severe scenarios.",
                G.LINEAGE,
                "Observed rainfall and request inputs retain lineage while tide, blockage, outage, and response effects remain explicit assumptions.",
                H.WEEKS,
                S.CITYWIDE,
                (M.FORECAST, M.SIMULATION, M.OPTIMIZATION),
                (R.MUNICIPAL_DEMAND, R.OPERATING_CAPACITY),
                "Existing drainage capacity and response protocols face compound rainfall without added redundancy.",
                (
                    "add backup power to critical pumps",
                    "pre-clear bottlenecks and stage mobile response capacity",
                    "select a robust mixed continuity portfolio across severe scenarios",
                ),
                "Do not claim precipitation caused observed requests or that assumed flood losses were observed.",
                existing_template_ref="deep.climate.rainfall-continuity.v1",
            ),
            seed(
                D.EVALUATE,
                "green-infrastructure-effect",
                "Evaluate distributed green-infrastructure effects",
                "Did phased green-infrastructure installation reduce verified runoff and disruption relative to credible comparisons?",
                "phased green-infrastructure installation",
                "matched catchment difference-in-differences evaluation",
                "change in event runoff volume",
                "cubic meters per event",
                C.TECHNICAL,
                "Treated and comparison catchments must have stable monitoring, comparable storms, and no unmodeled drainage redesign.",
                G.IDENTIFICATION,
                "Installation dates, comparable catchments, pre-trends, event normalization, spillover checks, and sensor diagnostics pass.",
                H.MULTI_YEAR,
                S.SERVICE_AREA,
                (M.DESCRIPTIVE, M.CAUSAL),
                (R.INTERVENTION_ASSIGNMENT, R.OUTCOME_PANEL, R.ENVIRONMENTAL_EXPOSURE),
                "Monitored catchments continue without the phased green-infrastructure installation.",
                (
                    "compare treated catchments with matched untreated catchments",
                    "estimate effects by installation type and storm intensity",
                    "test combined runoff and service-disruption outcomes",
                ),
                "Do not infer causal flood reduction from post-installation complaints alone.",
            ),
        ),
    ),
    FamilySeed(
        family_id="climate.wildfire-smoke",
        suite=SUITE,
        title="Wildfire smoke and air-quality resilience",
        description=(
            "Decision designs for smoke exposure, episode forecasting, building filtration, clean-air "
            "siting, supply allocation, activity scheduling, prolonged-event continuity, and evaluation."
        ),
        affected_system="urban smoke exposure and clean-air protection system",
        decision_owner="air-quality response coordinator and public-health director",
        common_source_roles=(R.CLIMATE_HAZARD, R.ENVIRONMENTAL_EXPOSURE, R.GEOGRAPHIC_IDENTITY),
        common_assumptions=(
            "Air-quality observations carry calibration, siting, and temporal metadata.",
            "Indoor infiltration and filtration effects are measured locally or labeled assumptions.",
        ),
        transportability_risks=(
            "Smoke chemistry, building leakage, monitor density, and household behavior differ.",
            "Regional forecasts and satellite products may have city-specific resolution limits.",
        ),
        claim_boundary=CLIMATE_BOUNDARY,
        designs=(
            seed(
                D.DIAGNOSE,
                "smoke-protection-gaps",
                "Diagnose smoke-exposure and clean-air protection gaps",
                "Which populations experience repeated smoke exposure without reliable indoor clean-air protection?",
                "population smoke-exposure and protection gaps",
                "monitor-satellite-building vulnerability triangulation",
                "people in high-exposure low-protection conditions",
                "people",
                C.EQUITY,
                "Protection-gap estimates must preserve uncertainty where monitor or building data are sparse.",
                G.GEOGRAPHIC_ALIGNMENT,
                "Monitor footprints, satellite grids, building records, and population estimates align to declared geographies.",
                H.SEASONAL,
                S.NEIGHBORHOOD,
                (M.DESCRIPTIVE,),
                (R.FACILITY_INVENTORY, R.EQUITY_ATTRIBUTE),
                "Existing filtration and public clean-air resources remain unchanged.",
                (
                    "verify protection conditions in the largest apparent gaps",
                    "target portable filtration support to confirmed high-risk households",
                    "combine building upgrades with accessible public clean-air spaces",
                ),
                "Do not label modeled particulate exposure as an individual dose or diagnosis.",
            ),
            seed(
                D.FORECAST,
                "smoke-episode-load",
                "Forecast smoke episode intensity and service load",
                "What probabilistic smoke and assistance-demand envelope should local operations prepare for?",
                "daily smoke episode and assistance load",
                "ensemble smoke-transport and demand forecasting",
                "service demand above clean-air response capacity",
                "requests per day",
                C.CAPACITY,
                "Activation forecasts must expose uncertainty and cannot exceed the spatial resolution of validated inputs.",
                G.CALIBRATION,
                "Held-out episodes meet particulate concentration, threshold-event, timing, and interval-coverage criteria.",
                H.DAYS,
                S.CITYWIDE,
                (M.FORECAST,),
                (R.MUNICIPAL_DEMAND, R.OPERATING_CAPACITY, R.REAL_TIME_STATE),
                "Ordinary air-quality communication and facility operations continue.",
                (
                    "activate communications from monitored thresholds",
                    "stage clean-air operations from ensemble risk bands",
                    "reserve capacity using upper prediction bounds for vulnerable groups",
                ),
                "Do not present regional smoke forecasts as measured neighborhood exposure.",
            ),
            seed(
                D.PRIORITIZE,
                "filtration-retrofits",
                "Prioritize public-building filtration retrofits",
                "Which public buildings should receive filtration and envelope upgrades first under limited capital?",
                "public-building smoke-protection retrofit portfolio",
                "risk- and occupancy-weighted retrofit prioritization",
                "vulnerable occupant-hours above indoor particulate thresholds",
                "occupant-hours",
                C.BUDGET,
                "Retrofit selection must fit capital, filter-replacement, energy, and maintenance budgets.",
                G.COST_CAPACITY,
                "Each building has verified occupancy, envelope, HVAC, retrofit cost, maintenance, and performance evidence.",
                H.MULTI_YEAR,
                S.FACILITY,
                (M.DESCRIPTIVE, M.OPTIMIZATION),
                (R.ASSET_INVENTORY, R.ASSET_CONDITION, R.FINANCIAL_COST, R.OPERATING_CAPACITY),
                "Buildings retain current filtration and envelope performance.",
                (
                    "retrofit highest vulnerable-occupancy facilities",
                    "fund lower-cost portable filtration across more sites",
                    "balance permanent HVAC upgrades with deployable clean-air kits",
                ),
                "Do not call engineering performance assumptions measured indoor exposure reduction.",
            ),
            seed(
                D.SITE,
                "clean-air-centers",
                "Site a network of public clean-air centers",
                "Where should verified clean-air spaces operate to maximize safe access during smoke events?",
                "public clean-air center network",
                "capacitated location-allocation with indoor-air qualification",
                "high-risk residents beyond a qualified clean-air space",
                "people",
                C.TECHNICAL,
                "Every selected center must pass indoor-air, power, accessible-entry, occupancy, and staffing requirements.",
                G.NETWORK_READINESS,
                "Qualified facilities and validated travel networks support time-specific accessibility estimates.",
                H.SEASONAL,
                S.FACILITY,
                (M.DESCRIPTIVE, M.OPTIMIZATION),
                (R.FACILITY_INVENTORY, R.TRANSPORT_NETWORK, R.OPERATING_CAPACITY),
                "Only currently certified clean-air facilities operate.",
                (
                    "open large qualified facilities near transit",
                    "add small neighborhood clean-air rooms in access gaps",
                    "combine fixed centers with transport and portable filtration support",
                ),
                "Do not call an ordinary public building a clean-air center without indoor-air verification.",
            ),
            seed(
                D.ALLOCATE,
                "filters-monitors-outreach",
                "Allocate filters, monitors, and smoke outreach",
                "How should limited filtration units, calibrated monitors, and outreach capacity be distributed?",
                "portable smoke-protection and monitoring resources",
                "needs- and uncertainty-aware allocation",
                "high-risk households without assigned protection capacity",
                "households",
                C.EQUITY,
                "Minimum protection shares for high-risk groups must be satisfied before residual allocation.",
                G.EQUITY_MEASUREMENT,
                "Eligibility denominators, exposure uncertainty, equipment inventory, and distribution records are auditable.",
                H.WEEKS,
                S.POPULATION_GROUP,
                (M.SIMULATION, M.OPTIMIZATION),
                (R.OPERATING_CAPACITY, R.EQUITY_ATTRIBUTE, R.COMMUNITY_INPUT),
                "Available equipment follows the existing first-come distribution process.",
                (
                    "allocate by verified medical and building vulnerability criteria",
                    "reserve monitors for data-sparse high-risk areas",
                    "adapt distribution using uptake and indoor-air follow-up evidence",
                ),
                "Do not report allocated equipment as installed, used correctly, or clinically effective.",
            ),
            seed(
                D.SCHEDULE,
                "smoke-safe-activities",
                "Schedule outdoor work, school, and public activities during smoke",
                "When should outdoor activities shift, shorten, move indoors, or resume as air quality changes?",
                "smoke-responsive activity and workforce schedule",
                "forecast-threshold scheduling with exposure budgets",
                "scheduled participant-hours above exposure limits",
                "participant-hours",
                C.REGULATORY,
                "Schedules must comply with occupational, school, accessibility, and emergency communication rules.",
                G.TEMPORAL_ALIGNMENT,
                "Air-quality issue times, local monitors, forecasts, activity calendars, and notification lead times align.",
                H.DAYS,
                S.FACILITY,
                (M.FORECAST, M.OPTIMIZATION),
                (R.SERVICE_SCHEDULE, R.LEGAL_REGULATORY, R.REAL_TIME_STATE),
                "Activities follow their ordinary calendar with existing threshold guidance.",
                (
                    "cancel activities at conservative measured thresholds",
                    "move vulnerable participants indoors before general cancellation",
                    "use rolling forecasts and exposure budgets to reschedule activities",
                ),
                "Do not treat a schedule rule as proof of participant exposure or compliance.",
            ),
            seed(
                D.STRESS_TEST,
                "prolonged-smoke-continuity",
                "Stress-test prolonged smoke-response continuity",
                "Can clean-air facilities, filters, staff, and communications sustain a multi-week smoke episode?",
                "prolonged-smoke response continuity plan",
                "inventory-depletion and facility-failure simulation",
                "scenario-weighted days below minimum clean-air coverage",
                "days",
                C.RISK,
                "Minimum clean-air coverage for high-risk populations must hold under supply and facility failure scenarios.",
                G.EXTERNAL_VALIDATION,
                "Infiltration, filter life, demand, failure, and replenishment parameters have external or local validation ranges.",
                H.WEEKS,
                S.CITYWIDE,
                (M.SIMULATION, M.OPTIMIZATION),
                (R.FACILITY_INVENTORY, R.OPERATING_CAPACITY, R.FINANCIAL_COST),
                "Existing filter stocks and facility plans face prolonged smoke without replenishment changes.",
                (
                    "increase pre-season filter inventory",
                    "create redundant clean-air sites and rotating staff",
                    "adopt robust replenishment triggers across duration scenarios",
                ),
                "Do not present assumed smoke duration or equipment failure as a forecast event.",
            ),
            seed(
                D.EVALUATE,
                "filtration-program-effect",
                "Evaluate household filtration and outreach effects",
                "Did phased filtration support reduce measured indoor particulate exposure and unequal protection?",
                "phased household filtration and outreach program",
                "randomized encouragement or staggered-rollout causal evaluation",
                "change in indoor fine-particulate concentration",
                "micrograms per cubic meter",
                C.EQUITY,
                "Attrition, device use, housing leakage, and subgroup effects must follow the pre-analysis plan.",
                G.IDENTIFICATION,
                "Assignment, uptake, calibrated indoor panels, outdoor controls, pre-periods, attrition, and spillover diagnostics pass.",
                H.SEASONAL,
                S.POPULATION_GROUP,
                (M.DESCRIPTIVE, M.CAUSAL),
                (R.INTERVENTION_ASSIGNMENT, R.OUTCOME_PANEL, R.EQUITY_ATTRIBUTE),
                "Eligible households continue without the phased filtration offer.",
                (
                    "estimate offer effects under randomized encouragement",
                    "estimate rollout effects using not-yet-treated comparisons",
                    "measure heterogeneity by building leakage and baseline vulnerability",
                ),
                "Do not interpret device receipt as use or indoor particulate change as a clinical outcome.",
            ),
        ),
    ),
    FamilySeed(
        family_id="climate.drought-water",
        suite=SUITE,
        title="Drought and urban water security",
        description=(
            "Decision designs for water loss diagnosis, demand and supply forecasting, renewal and "
            "reuse investment, distribution, scheduling, multi-year stress, and conservation evaluation."
        ),
        affected_system="urban water supply, distribution, and conservation system",
        decision_owner="water utility general manager and drought-response lead",
        common_source_roles=(R.CLIMATE_HAZARD, R.ASSET_INVENTORY, R.OPERATING_CAPACITY),
        common_assumptions=(
            "Supply, demand, leakage, and storage balances use reconciled units and meter coverage.",
            "Restriction response and climate sequences are observed inputs or labeled scenarios.",
        ),
        transportability_risks=(
            "Water rights, source portfolios, pricing, metering, leakage, and climate regimes differ.",
            "Household conservation behavior may not transfer across tariff and tenure systems.",
        ),
        claim_boundary=CLIMATE_BOUNDARY,
        designs=(
            seed(
                D.DIAGNOSE,
                "water-loss-balance",
                "Diagnose non-revenue water and demand anomalies",
                "Which zones show persistent production-consumption imbalance after meter uncertainty and authorized uses are reconciled?",
                "distribution-zone water balance anomalies",
                "metered mass-balance and change-point diagnosis",
                "unexplained distribution water volume",
                "cubic meters per day",
                C.TECHNICAL,
                "An anomaly must exceed combined production, customer-meter, and boundary-flow uncertainty.",
                G.COMPLETENESS,
                "Production, transfer, customer meter, authorized-use, and asset-zone records meet declared coverage thresholds.",
                H.ANNUAL,
                S.SERVICE_AREA,
                (M.DESCRIPTIVE,),
                (R.ASSET_CONDITION, R.REAL_TIME_STATE),
                "Current leakage detection and meter replacement continue.",
                (
                    "validate meters in the largest unexplained zones",
                    "deploy pressure and acoustic monitoring to persistent anomalies",
                    "combine meter correction with targeted leak investigation",
                ),
                "Do not label balance residuals as confirmed leaks or unauthorized consumption.",
            ),
            seed(
                D.FORECAST,
                "drought-supply-demand",
                "Forecast drought supply-demand balance",
                "What seasonal probability distribution of storage and shortage follows climate, demand, and operating assumptions?",
                "seasonal urban water supply-demand balance",
                "ensemble hydrologic and demand balance forecasting",
                "expected potable-water shortage volume",
                "cubic meters",
                C.RISK,
                "Forecast operations must preserve the adopted emergency storage and environmental-flow reserve.",
                G.CALIBRATION,
                "Hindcasts meet inflow, demand, storage, shortage-event, and interval-coverage criteria across dry years.",
                H.SEASONAL,
                S.CITYWIDE,
                (M.FORECAST, M.SIMULATION),
                (R.ENVIRONMENTAL_EXPOSURE, R.FINANCIAL_COST),
                "Existing sources, tariffs, and operating rules continue through the forecast horizon.",
                (
                    "activate conservation from median storage projections",
                    "use conservative triggers tied to lower inflow bounds",
                    "coordinate source switching and demand stages across ensemble scenarios",
                ),
                "Do not call a climate-conditioned water balance a deterministic shortage prediction.",
            ),
            seed(
                D.PRIORITIZE,
                "water-security-portfolio",
                "Prioritize leakage, reuse, and supply-reliability investments",
                "Which investments best reduce shortage and failure risk within capital and operating limits?",
                "water-security capital and conservation portfolio",
                "reliability-adjusted multi-period portfolio optimization",
                "expected annual shortage and leakage volume",
                "cubic meters per year",
                C.BUDGET,
                "Selected projects must fit capital, energy, treatment, maintenance, and delivery-capacity limits.",
                G.COST_CAPACITY,
                "Project yield, reliability, cost, energy, permitting, dependencies, and delivery evidence are independently reviewed.",
                H.MULTI_YEAR,
                S.ASSET,
                (M.SIMULATION, M.OPTIMIZATION),
                (R.ASSET_CONDITION, R.FINANCIAL_COST, R.LEGAL_REGULATORY),
                "Only committed water-security projects proceed.",
                (
                    "prioritize verified leakage reduction",
                    "expand non-potable reuse where treatment and demand align",
                    "select a diversified supply, efficiency, and renewal portfolio",
                ),
                "Do not report modeled yield or avoided shortage as delivered water.",
            ),
            seed(
                D.SITE,
                "reuse-storage-facilities",
                "Site water reuse and distributed storage facilities",
                "Where can reuse treatment or storage connect feasible supply to demand with acceptable environmental and community burdens?",
                "water reuse and distributed storage locations",
                "network-constrained source-demand facility siting",
                "unserved reliable non-potable water demand",
                "cubic meters per day",
                C.ENVIRONMENTAL,
                "Sites must meet water-quality, discharge, land, energy, permitting, and community-burden constraints.",
                G.LEGAL_AUTHORITY,
                "Water rights, parcel control, treatment approval, discharge permits, and responsible operators are documented.",
                H.MULTI_YEAR,
                S.FACILITY,
                (M.SIMULATION, M.OPTIMIZATION),
                (R.LAND_PARCEL, R.LEGAL_REGULATORY, R.FINANCIAL_COST, R.TRANSPORT_NETWORK),
                "No additional reuse or storage facilities are built.",
                (
                    "locate treatment near stable non-potable demand",
                    "site neighborhood storage near pressure and outage risks",
                    "co-optimize reuse facilities, pipelines, and storage",
                ),
                "Do not describe a screened location as permitted, engineered, or publicly accepted.",
            ),
            seed(
                D.ALLOCATE,
                "scarce-water-allocation",
                "Allocate scarce water across essential uses",
                "How should constrained supply be allocated while protecting essential, environmental, and equity requirements?",
                "drought-period water allocation",
                "lexicographic essential-use and equity allocation",
                "essential demand left unmet",
                "cubic meters per day",
                C.REGULATORY,
                "Allocation must honor water rights, public-health minimums, environmental flows, and adopted drought rules.",
                G.LEGAL_AUTHORITY,
                "Legal priorities, essential-use definitions, allocation authority, metered demand, and enforcement mechanisms are current.",
                H.WEEKS,
                S.SERVICE_AREA,
                (M.SIMULATION, M.OPTIMIZATION),
                (R.LEGAL_REGULATORY, R.EQUITY_ATTRIBUTE, R.REAL_TIME_STATE),
                "Existing drought allocation rules remain unchanged.",
                (
                    "protect essential-use floors before discretionary supply",
                    "allocate conservation obligations by feasible demand reduction",
                    "adapt zone allocations to observed storage and critical demand",
                ),
                "Do not present a modeled scarcity allocation as a lawful order or delivered volume.",
            ),
            seed(
                D.SCHEDULE,
                "drought-operations",
                "Schedule drought operations, maintenance, and restrictions",
                "When should source switching, maintenance, irrigation limits, and restriction stages occur?",
                "drought operating and restriction calendar",
                "storage-triggered multi-period operations scheduling",
                "days below emergency storage reserve",
                "days",
                C.TIME,
                "Treatment, conveyance, maintenance, notice, and restriction lead times must be respected.",
                G.TEMPORAL_ALIGNMENT,
                "Storage, inflow, demand, maintenance, legal notice, and restriction records share effective dates and update cadence.",
                H.SEASONAL,
                S.CITYWIDE,
                (M.FORECAST, M.OPTIMIZATION),
                (R.SERVICE_SCHEDULE, R.LEGAL_REGULATORY, R.REAL_TIME_STATE),
                "The utility follows its ordinary seasonal operations calendar.",
                (
                    "advance planned maintenance before low-storage periods",
                    "trigger restrictions from conservative storage bands",
                    "jointly schedule sources, maintenance, and staged conservation",
                ),
                "Do not call an optimized calendar an adopted restriction or completed maintenance plan.",
            ),
            seed(
                D.STRESS_TEST,
                "multi-year-water-security",
                "Stress-test multi-year urban water security",
                "Which portfolio sustains essential supply across prolonged drought, infrastructure failure, and demand uncertainty?",
                "multi-year water-security strategy",
                "stochastic storage and infrastructure reliability simulation",
                "scenario-weighted essential shortage volume",
                "cubic meters",
                C.RISK,
                "Essential-service reliability must exceed the declared threshold across severe climate and asset-failure scenarios.",
                G.EXTERNAL_VALIDATION,
                "Hydrology, demand elasticity, failure, repair, project-yield, and climate-sequence ranges have independent support.",
                H.MULTI_YEAR,
                S.CITYWIDE,
                (M.FORECAST, M.SIMULATION, M.OPTIMIZATION),
                (R.ASSET_CONDITION, R.FINANCIAL_COST, R.ENVIRONMENTAL_EXPOSURE),
                "Current sources and renewal plans face the multi-year scenario without additional measures.",
                (
                    "accelerate leakage reduction and emergency interconnections",
                    "add modular reuse and storage capacity",
                    "select a robust staged portfolio across climate sequences",
                ),
                "Do not present synthetic drought sequences as forecasts or assumed project yield as observed supply.",
            ),
            seed(
                D.EVALUATE,
                "conservation-incentive-effect",
                "Evaluate conservation pricing and assistance effects",
                "Did a phased conservation incentive reduce discretionary demand without burdening essential use?",
                "phased water-conservation pricing and assistance program",
                "staggered policy causal evaluation with meter panels",
                "change in weather-normalized discretionary water demand",
                "liters per account-day",
                C.EQUITY,
                "Essential-use floors, affordability, treatment timing, and heterogeneous effects must be pre-specified.",
                G.IDENTIFICATION,
                "Dated eligibility, meter panels, comparable accounts, pre-trends, weather controls, spillovers, and billing changes are verified.",
                H.ANNUAL,
                S.POPULATION_GROUP,
                (M.DESCRIPTIVE, M.CAUSAL),
                (R.INTERVENTION_ASSIGNMENT, R.OUTCOME_PANEL, R.EQUITY_ATTRIBUTE, R.FINANCIAL_COST),
                "Eligible accounts retain the pre-program tariff and assistance conditions.",
                (
                    "compare phased eligible and not-yet-treated accounts",
                    "separate price, rebate, and technical-assistance components",
                    "estimate demand and affordability effects by baseline use group",
                ),
                "Do not infer welfare gains from lower consumption or causal effects from simple before-after billing totals.",
            ),
        ),
    ),
    FamilySeed(
        family_id="climate.coastal-storms",
        suite=SUITE,
        title="Coastal storms and sea-level adaptation",
        description=(
            "Decision designs for coastal exposure diagnosis, surge forecasting, adaptation portfolios, "
            "protective siting, emergency allocation, closure timing, compound stress, and evaluation."
        ),
        affected_system="coastal protection, evacuation, and long-term adaptation system",
        decision_owner="coastal resilience director and emergency-management commissioner",
        common_source_roles=(R.CLIMATE_HAZARD, R.GEOGRAPHIC_IDENTITY, R.ASSET_INVENTORY),
        common_assumptions=(
            "Elevation, surge, shoreline, asset, and population layers share documented vertical and horizontal datums.",
            "Sea-level pathways, damage functions, and adaptation performance remain explicit scenarios.",
        ),
        transportability_risks=(
            "Coastal morphology, tides, subsidence, protection standards, and evacuation behavior differ.",
            "Long-horizon adaptation values depend on local finance, land tenure, and legal authority.",
        ),
        claim_boundary=CLIMATE_BOUNDARY,
        designs=(
            seed(
                D.DIAGNOSE,
                "coastal-dependency-exposure",
                "Diagnose coastal asset exposure and service dependencies",
                "Which critical services depend on coastal assets exposed across surge and sea-level pathways?",
                "coastal critical-asset and dependency exposure",
                "datum-aligned inundation and service-dependency graph analysis",
                "critical service dependencies exposed to coastal flooding",
                "dependencies",
                C.TECHNICAL,
                "Exposure findings require verified elevation, protection, asset function, and dependency records.",
                G.GEOGRAPHIC_ALIGNMENT,
                "Surge surfaces, elevation, defenses, parcels, assets, and service areas use reconciled datums and geometries.",
                H.MULTI_YEAR,
                S.NETWORK,
                (M.DESCRIPTIVE,),
                (R.ASSET_CONDITION, R.FACILITY_INVENTORY, R.ENVIRONMENTAL_EXPOSURE),
                "Existing coastal defenses and service dependencies remain unchanged.",
                (
                    "verify high-consequence exposure and hidden dependencies",
                    "protect operational continuity for repeatedly exposed assets",
                    "reduce dependency concentration through redundancy and relocation",
                ),
                "Do not equate mapped inundation exposure with observed damage or failure.",
            ),
            seed(
                D.FORECAST,
                "storm-surge-operations",
                "Forecast coastal storm operational impacts",
                "What probabilistic surge, access, outage, and response-demand envelope should operations use?",
                "event-level coastal storm operational impacts",
                "ensemble surge-to-service impact forecasting",
                "critical service demand above operable capacity",
                "service-units per event",
                C.RISK,
                "Operational forecasts must retain uncertainty from storm track, tide, protection state, and damage translation.",
                G.CALIBRATION,
                "Historical events meet surge-height, inundation-extent, access-loss, outage, and interval-coverage criteria.",
                H.DAYS,
                S.CITYWIDE,
                (M.FORECAST, M.SIMULATION),
                (R.REAL_TIME_STATE, R.OPERATING_CAPACITY, R.MUNICIPAL_DEMAND),
                "Existing storm protocols activate from current official thresholds.",
                (
                    "activate from official surge thresholds",
                    "pre-position resources using ensemble exceedance probabilities",
                    "reserve capacity against upper-bound access and outage scenarios",
                ),
                "Do not present forecast inundation or outage as an observed impact.",
            ),
            seed(
                D.PRIORITIZE,
                "coastal-adaptation-portfolio",
                "Prioritize coastal protection, accommodation, and retreat",
                "Which phased adaptation portfolio best preserves services and equity under uncertain sea-level pathways?",
                "coastal adaptation investment portfolio",
                "adaptive-pathway portfolio optimization",
                "expected critical-service disruption across sea-level pathways",
                "service-days",
                C.BUDGET,
                "The portfolio must fit capital, maintenance, acquisition, financing, and delivery constraints by phase.",
                G.COST_CAPACITY,
                "Costs, protection performance, triggers, dependencies, land impacts, and residual risk receive independent review.",
                H.MULTI_YEAR,
                S.ASSET,
                (M.SIMULATION, M.OPTIMIZATION),
                (R.ASSET_CONDITION, R.FINANCIAL_COST, R.LAND_PARCEL, R.EQUITY_ATTRIBUTE),
                "Only already-funded coastal projects proceed.",
                (
                    "protect high-consequence existing assets",
                    "accommodate flooding through elevation and redundancy",
                    "use trigger-based protection, accommodation, and voluntary retreat pathways",
                ),
                "Do not call modeled avoided loss a realized benefit or a pathway an adopted land policy.",
            ),
            seed(
                D.SITE,
                "coastal-shelter-logistics",
                "Site coastal shelters and resilient logistics hubs",
                "Where should shelters and logistics hubs remain accessible outside compound surge, wind, and outage exposure?",
                "coastal shelter and emergency-logistics locations",
                "multi-hazard capacitated facility siting with evacuation access",
                "at-risk population beyond safe shelter capacity",
                "people",
                C.RISK,
                "Candidate sites must remain operable under design surge, wind, access, power, and supply scenarios.",
                G.NETWORK_READINESS,
                "Facilities, evacuation networks, capacities, hazards, travel times, and failure dependencies pass validation.",
                H.MULTI_YEAR,
                S.FACILITY,
                (M.SIMULATION, M.OPTIMIZATION),
                (R.FACILITY_INVENTORY, R.TRANSPORT_NETWORK, R.OPERATING_CAPACITY),
                "Only existing designated shelters and depots operate.",
                (
                    "upgrade existing low-exposure high-access facilities",
                    "add distributed neighborhood shelters outside surge zones",
                    "co-site shelter, backup power, and emergency logistics capacity",
                ),
                "Do not label a candidate facility safe without structural, access, and continuity verification.",
            ),
            seed(
                D.ALLOCATE,
                "coastal-emergency-resources",
                "Allocate coastal emergency transport and supplies",
                "How should accessible transport, rescue assets, generators, and supplies be staged before landfall?",
                "pre-landfall coastal emergency resources",
                "scenario-robust staging and allocation optimization",
                "high-risk residents and critical sites without assigned support",
                "coverage units",
                C.TIME,
                "Staging, travel, loading, crew-safety, and evacuation-clearance times must fit the landfall window.",
                G.TEMPORAL_ALIGNMENT,
                "Forecast issue times, population registries, asset locations, route states, and logistics inventories pass freshness checks.",
                H.DAYS,
                S.NETWORK,
                (M.FORECAST, M.SIMULATION, M.OPTIMIZATION),
                (R.TRANSPORT_NETWORK, R.REAL_TIME_STATE, R.OPERATING_CAPACITY, R.EQUITY_ATTRIBUTE),
                "Resources remain at ordinary depots under existing staging plans.",
                (
                    "stage assets by official evacuation zones",
                    "reserve accessible transport and power for registered critical needs",
                    "optimize robust staging across track and network-failure scenarios",
                ),
                "Do not report a staged resource plan as completed evacuation or delivered assistance.",
            ),
            seed(
                D.SCHEDULE,
                "coastal-closure-evacuation",
                "Schedule coastal closures and phased evacuation",
                "When should ports, roads, services, and evacuation zones transition before a coastal storm?",
                "phased coastal closure and evacuation timetable",
                "clearance-time and forecast-trigger scheduling",
                "population remaining in risk zones at unsafe conditions",
                "people",
                C.TIME,
                "Each phase must satisfy clearance time, transport capacity, worker safety, and public-notice lead time.",
                G.NETWORK_READINESS,
                "Validated demand, route capacity, transit schedules, control points, and disruption states support clearance estimates.",
                H.DAYS,
                S.NETWORK,
                (M.FORECAST, M.SIMULATION, M.OPTIMIZATION),
                (R.TRANSPORT_NETWORK, R.SERVICE_SCHEDULE, R.REAL_TIME_STATE, R.LEGAL_REGULATORY),
                "Current fixed evacuation and closure triggers remain in effect.",
                (
                    "phase evacuation by official risk zone",
                    "prioritize carless and assisted populations before general departure",
                    "adapt closure and evacuation timing to ensemble tracks and observed network state",
                ),
                "Do not call simulated clearance an actual evacuation result or assume universal compliance.",
            ),
            seed(
                D.STRESS_TEST,
                "compound-coastal-failure",
                "Stress-test coastal systems under compound failure",
                "Which adaptation and continuity strategy survives surge, rain, wind, power, access, and supply-chain failures?",
                "compound coastal continuity strategy",
                "correlated multi-hazard dependency simulation",
                "scenario-weighted critical service outage duration",
                "service-hours",
                C.RISK,
                "Life-safety and critical-service thresholds must hold under severe correlated failure scenarios.",
                G.EXTERNAL_VALIDATION,
                "Hazard dependence, fragility, restoration, demand, and adaptation-performance ranges have documented validation.",
                H.WEEKS,
                S.NETWORK,
                (M.FORECAST, M.SIMULATION, M.OPTIMIZATION),
                (R.ASSET_CONDITION, R.OPERATING_CAPACITY, R.FINANCIAL_COST),
                "Existing defenses and continuity plans face compound failure without added measures.",
                (
                    "harden critical nodes and add backup power",
                    "create geographically diverse service redundancy",
                    "use adaptive recovery portfolios robust to correlated failures",
                ),
                "Do not describe synthetic compound failures as forecast probabilities without calibrated dependence evidence.",
            ),
            seed(
                D.EVALUATE,
                "coastal-adaptation-effect",
                "Evaluate property-level coastal adaptation effects",
                "Did phased elevation or voluntary acquisition reduce verified loss and displacement burden?",
                "phased property elevation and voluntary acquisition program",
                "matched event-study evaluation across comparable exposed properties",
                "change in event-related verified loss",
                "currency per property-event",
                C.EQUITY,
                "Selection, insurance, mobility, spillovers, attrition, and displacement outcomes must be pre-specified and observed.",
                G.IDENTIFICATION,
                "Assignment timing, comparable properties, pre-trends, hazard intensity, verified loss panels, moves, and spillover tests pass.",
                H.MULTI_YEAR,
                S.PARCEL,
                (M.DESCRIPTIVE, M.CAUSAL),
                (R.INTERVENTION_ASSIGNMENT, R.OUTCOME_PANEL, R.HOUSING_MARKET, R.EQUITY_ATTRIBUTE),
                "Eligible exposed properties continue without the phased adaptation offer.",
                (
                    "compare phased elevation recipients with not-yet-treated properties",
                    "estimate voluntary acquisition effects on loss and relocation stability",
                    "evaluate heterogeneous effects by tenure and baseline vulnerability",
                ),
                "Do not infer causal protection or equitable relocation from selected participant outcomes alone.",
            ),
        ),
    ),
)

__all__ = ["CLIMATE_FAMILIES"]
