"""Thirty-two population-health and environmental-exposure decision designs."""

# ruff: noqa: E501 -- long policy statements are indivisible catalog content.

from civicdecision.deep.models import ApplicationSuite
from civicdecision.scenario_library.matrix import axis, matrix_family
from civicdecision.scenario_library.seeds import D, R, S

SUITE = ApplicationSuite.POPULATION_HEALTH
BOUNDARY = (
    "Area exposure, service, and vulnerability records do not diagnose individuals or prove harm.",
    "Operational allocations are proposed planning outputs, not delivered clinical or social services.",
    "Health-effect claims require outcome panels, identification, privacy, and external review.",
)


HEALTH_FAMILIES = (
    matrix_family(
        family_id="health.heat-health",
        suite=SUITE,
        title="Heat-health surveillance and prevention",
        description=(
            "Eight health-centered decisions for syndrome diagnosis, demand forecasting, prevention "
            "investment, care access, outreach allocation, surveillance timing, surge stress, and evaluation."
        ),
        affected_system="heat-health surveillance, prevention, and care coordination",
        decision_owner="public-health preparedness director and emergency medical services lead",
        common_source_roles=(R.HEALTH_OUTCOME, R.CLIMATE_HAZARD, R.DEMOGRAPHIC_CONTEXT),
        common_assumptions=(
            "Health records are privacy-preserving, population-defined, timely, and separated from service-request proxies.",
            "Heat exposure, care seeking, reporting, and intervention effects remain distinct constructs.",
        ),
        transportability_risks=(
            "Clinical coding, surveillance coverage, acclimatization, housing, and care access vary.",
            "Small-area health estimates may be unstable or disclosure-sensitive.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "heat-illness-patterns",
                "Diagnose heat-health surveillance patterns",
                "Where and when do verified heat-related syndromes diverge from expected seasonal and reporting patterns?",
                "heat-related syndrome and surveillance anomalies",
                "exposure-linked spatiotemporal surveillance diagnosis",
                "unexplained excess heat-related health events",
                "events",
                S.POPULATION_GROUP,
                (R.ENVIRONMENTAL_EXPOSURE, R.EQUITY_ATTRIBUTE),
                "Do not diagnose individuals or attribute events to heat from aggregate temporal overlap.",
            ),
            axis(
                D.FORECAST,
                "heat-care-demand",
                "Forecast heat-related care and outreach demand",
                "What probabilistic emergency, call-center, and outreach workload should health operations prepare for?",
                "daily heat-health care and outreach demand",
                "lag-aware heat-health workload forecasting",
                "health-response demand above staffed capacity",
                "encounters per day",
                S.SERVICE_AREA,
                (R.OPERATING_CAPACITY, R.REAL_TIME_STATE),
                "Do not present forecast encounters as illnesses, admissions, or deaths.",
            ),
            axis(
                D.PRIORITIZE,
                "heat-prevention-portfolio",
                "Prioritize heat-health prevention investments",
                "Which surveillance, housing, clinical, outreach, and cooling measures should enter the prevention portfolio?",
                "heat-health prevention investment portfolio",
                "health-burden, equity, and deliverability portfolio optimization",
                "expected preventable heat-health burden",
                "quality-adjusted health-event equivalents",
                S.ASSET,
                (R.FINANCIAL_COST, R.FACILITY_INVENTORY, R.EQUITY_ATTRIBUTE),
                "Do not report modeled preventable burden as avoided illness or mortality.",
            ),
            axis(
                D.SITE,
                "heat-health-access-points",
                "Site heat-health assessment and respite access points",
                "Where should non-emergency assessment, respite, and referral sites operate during heat events?",
                "heat-health assessment and referral locations",
                "care-access facility location with clinical escalation constraints",
                "high-risk residents beyond timely heat-health support",
                "people",
                S.FACILITY,
                (R.FACILITY_INVENTORY, R.TRANSPORT_NETWORK, R.OPERATING_CAPACITY),
                "Do not call a community facility a clinical site or safe respite without qualification.",
            ),
            axis(
                D.ALLOCATE,
                "heat-health-outreach",
                "Allocate heat-health outreach and clinical surge support",
                "How should community health workers, call capacity, transport, and clinical surge slots be distributed?",
                "heat-health outreach and surge resources",
                "risk-, access-, and minimum-coverage allocation",
                "high-risk people without assigned support capacity",
                "people",
                S.POPULATION_GROUP,
                (R.OPERATING_CAPACITY, R.EQUITY_ATTRIBUTE, R.REAL_TIME_STATE),
                "Do not report assigned support as contacted patients, completed visits, or improved health.",
            ),
            axis(
                D.SCHEDULE,
                "heat-health-surveillance",
                "Schedule heat-health surveillance and response escalation",
                "When should surveillance refresh, outreach, clinical staffing, and escalation thresholds activate?",
                "heat-health surveillance and escalation schedule",
                "forecast- and syndrome-triggered operations scheduling",
                "hours of high-risk conditions without active health response",
                "hours",
                S.CITYWIDE,
                (R.SERVICE_SCHEDULE, R.OPERATING_CAPACITY, R.REAL_TIME_STATE),
                "Do not call an escalation schedule activated or a health response delivered.",
            ),
            axis(
                D.STRESS_TEST,
                "heat-health-surge",
                "Stress-test heat-health surge capacity",
                "Which prevention and care strategy preserves essential capacity during prolonged heat, outages, and staff loss?",
                "heat-health system continuity under compound surge",
                "care-demand, power, facility, and staffing failure simulation",
                "scenario-weighted unmet critical heat-health demand",
                "encounters",
                S.NETWORK,
                (R.OPERATING_CAPACITY, R.FACILITY_INVENTORY, R.ASSET_CONDITION),
                "Do not present simulated patient loads or failures as an epidemic forecast or observed harm.",
            ),
            axis(
                D.EVALUATE,
                "heat-outreach-effect",
                "Evaluate targeted heat-health outreach",
                "Did phased proactive outreach reduce verified emergency heat-health events without unequal exclusion?",
                "phased proactive heat-health outreach program",
                "randomized encouragement or staggered rollout evaluation",
                "change in verified heat-related emergency encounters",
                "encounters per ten thousand people",
                S.POPULATION_GROUP,
                (R.EQUITY_ATTRIBUTE, R.COMMUNITY_INPUT),
                "Do not infer mortality or causal protection without validated outcomes and assignment diagnostics.",
            ),
        ),
    ),
    matrix_family(
        family_id="health.air-quality",
        suite=SUITE,
        title="Air-quality exposure and respiratory health",
        description=(
            "Eight decisions for exposure-health diagnosis, syndrome forecasting, mitigation portfolios, "
            "monitor siting, protection allocation, alert timing, pollution stress, and program evaluation."
        ),
        affected_system="air-quality surveillance, exposure reduction, and respiratory-health response",
        decision_owner="environmental health director and air-quality program lead",
        common_source_roles=(R.ENVIRONMENTAL_EXPOSURE, R.HEALTH_OUTCOME, R.GEOGRAPHIC_IDENTITY),
        common_assumptions=(
            "Monitor data retain calibration, siting, uptime, and spatial-representativeness metadata.",
            "Exposure, diagnosis, care use, and service complaints are not interchangeable outcomes.",
        ),
        transportability_risks=(
            "Pollutant mixtures, indoor infiltration, source profiles, coding, and monitor coverage differ.",
            "Modeled concentration may not represent personal exposure.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "exposure-health-discordance",
                "Diagnose environmental exposure and respiratory-health patterns",
                "Which areas show persistent pollutant, respiratory, and service signals after coverage differences are separated?",
                "air-exposure and respiratory-health pattern discordance",
                "multi-source exposure, outcome, and reporting triangulation",
                "unresolved high-exposure high-burden population",
                "people",
                S.NEIGHBORHOOD,
                (R.DEMOGRAPHIC_CONTEXT, R.MUNICIPAL_DEMAND, R.EQUITY_ATTRIBUTE),
                "Do not convert environmental request labels into measured exposure, diagnosis, or causal health risk.",
                existing_template_ref="deep.health.environmental-request-screen.v1",
            ),
            axis(
                D.FORECAST,
                "respiratory-demand",
                "Forecast air-quality alerts and respiratory service demand",
                "What pollutant and respiratory-service workload envelope should public-health operations prepare for?",
                "daily pollution alert and respiratory service demand",
                "weather-source and lag-conditioned joint forecasting",
                "respiratory response demand above available capacity",
                "encounters per day",
                S.SERVICE_AREA,
                (R.CLIMATE_HAZARD, R.OPERATING_CAPACITY, R.REAL_TIME_STATE),
                "Do not call forecast service demand diagnosed disease or pollutant-attributable illness.",
            ),
            axis(
                D.PRIORITIZE,
                "exposure-reduction-portfolio",
                "Prioritize air-exposure reduction investments",
                "Which source-control, building, monitoring, and health-protection measures should be funded first?",
                "air-exposure reduction and health-protection portfolio",
                "source, exposure, equity, and lifecycle project optimization",
                "population-weighted exposure above health-protection thresholds",
                "person-micrograms per cubic meter",
                S.ASSET,
                (R.ASSET_INVENTORY, R.FINANCIAL_COST, R.EQUITY_ATTRIBUTE),
                "Do not report modeled exposure reduction as avoided disease or realized emissions compliance.",
            ),
            axis(
                D.SITE,
                "monitor-protection-network",
                "Site monitors and clean-air health resources",
                "Where should calibrated monitoring and qualified protection resources fill population and uncertainty gaps?",
                "air-quality monitor and health-protection locations",
                "uncertainty-aware sensor and facility co-location",
                "high-risk population without representative monitoring or protection access",
                "people",
                S.FACILITY,
                (R.FACILITY_INVENTORY, R.LAND_PARCEL, R.EQUITY_ATTRIBUTE),
                "Do not call a low-cost sensor regulatory-grade or a candidate facility clinically qualified.",
            ),
            axis(
                D.ALLOCATE,
                "respiratory-protection",
                "Allocate respiratory protection and outreach resources",
                "How should filters, masks, clinical navigation, and outreach be distributed during pollution episodes?",
                "air-pollution respiratory protection resources",
                "exposure-, vulnerability-, and access-constrained allocation",
                "high-risk people without assigned protection support",
                "people",
                S.POPULATION_GROUP,
                (R.OPERATING_CAPACITY, R.EQUITY_ATTRIBUTE, R.COMMUNITY_INPUT),
                "Do not report distributed supplies as used correctly or clinically effective.",
            ),
            axis(
                D.SCHEDULE,
                "air-health-response",
                "Schedule air-quality alerts and health response",
                "When should monitoring review, alerts, outreach, indoor protection, and clinical surge activate?",
                "air-quality health alert and response schedule",
                "forecast-monitor-syndrome trigger scheduling",
                "high-exposure hours without active protection measures",
                "hours",
                S.CITYWIDE,
                (R.SERVICE_SCHEDULE, R.REAL_TIME_STATE, R.OPERATING_CAPACITY),
                "Do not call an alert schedule issued, received, understood, or acted upon.",
            ),
            axis(
                D.STRESS_TEST,
                "pollution-health-continuity",
                "Stress-test respiratory-health continuity during pollution episodes",
                "Which response strategy preserves clean-air and care capacity across prolonged pollution and facility failures?",
                "respiratory-health continuity under prolonged pollution",
                "pollution-duration, infiltration, demand, and facility failure simulation",
                "scenario-weighted unmet respiratory protection and care demand",
                "person-days",
                S.NETWORK,
                (R.OPERATING_CAPACITY, R.FACILITY_INVENTORY, R.ASSET_CONDITION),
                "Do not present synthetic episodes or care demand as forecasts or observed health burden.",
            ),
            axis(
                D.EVALUATE,
                "clean-air-program-effect",
                "Evaluate clean-air protection and source-control effects",
                "Did phased protection or source-control measures reduce measured exposure and verified respiratory events?",
                "phased clean-air protection and source-control intervention",
                "staggered adoption evaluation with exposure and health panels",
                "change in measured exposure and respiratory-event rate",
                "concentration and events per population",
                S.POPULATION_GROUP,
                (R.EQUITY_ATTRIBUTE, R.LEGAL_REGULATORY),
                "Do not infer causal health benefits without assignment, exposure, outcome, and spillover validity.",
            ),
        ),
    ),
    matrix_family(
        family_id="health.infectious-operations",
        suite=SUITE,
        title="Infectious-disease public-health operations",
        description=(
            "Eight operational decisions for surveillance diagnosis, workload forecasting, preparedness "
            "investment, service siting, supply allocation, clinic scheduling, surge stress, and evaluation."
        ),
        affected_system="privacy-preserving infectious-disease surveillance and response operations",
        decision_owner="communicable-disease director and public-health operations chief",
        common_source_roles=(R.HEALTH_OUTCOME, R.GEOGRAPHIC_IDENTITY, R.OPERATING_CAPACITY),
        common_assumptions=(
            "Case, syndrome, testing, wastewater, vaccination, and care records have explicit definitions and delays.",
            "No individual identity or protected health information enters public release artifacts.",
        ),
        transportability_risks=(
            "Pathogens, immunity, clinical practice, reporting, testing, and public behavior differ.",
            "Surveillance changes can mimic epidemiological changes.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "surveillance-discordance",
                "Diagnose infectious-disease surveillance discordance",
                "Which place-time signals remain unusual after testing, reporting delay, seasonality, and source coverage are reconciled?",
                "infectious-disease surveillance signal discordance",
                "multi-stream nowcast residual and change-point diagnosis",
                "unresolved abnormal surveillance signals",
                "signals",
                S.SERVICE_AREA,
                (R.ENVIRONMENTAL_EXPOSURE, R.DEMOGRAPHIC_CONTEXT),
                "Do not label an aggregate anomaly an outbreak, individual infection, or transmission source.",
            ),
            axis(
                D.FORECAST,
                "care-testing-demand",
                "Forecast infectious-disease care and testing demand",
                "What probabilistic clinic, testing, laboratory, hotline, and bed demand should operations prepare for?",
                "infectious-disease response workload",
                "reporting-delay-aware multistream demand forecasting",
                "care and testing demand above staffed capacity",
                "service encounters per day",
                S.SERVICE_AREA,
                (R.REAL_TIME_STATE, R.SERVICE_SCHEDULE),
                "Do not call forecast workload infections, admissions, or transmission.",
            ),
            axis(
                D.PRIORITIZE,
                "preparedness-portfolio",
                "Prioritize infectious-disease preparedness investments",
                "Which laboratory, ventilation, data, workforce, supply, and community measures best reduce response fragility?",
                "infectious-disease preparedness portfolio",
                "multi-pathogen readiness and lifecycle portfolio optimization",
                "expected essential response-capacity shortfall",
                "service-days",
                S.ASSET,
                (R.ASSET_INVENTORY, R.FINANCIAL_COST, R.COMMUNITY_INPUT),
                "Do not report modeled preparedness as prevented cases or completed capacity.",
            ),
            axis(
                D.SITE,
                "testing-vaccination-sites",
                "Site accessible testing, vaccination, and treatment access points",
                "Where should temporary health access points operate under demand, equity, cold-chain, and infection-control constraints?",
                "temporary infectious-disease service locations",
                "capacitated access and infection-control facility siting",
                "eligible population beyond timely qualified service access",
                "people",
                S.FACILITY,
                (R.FACILITY_INVENTORY, R.TRANSPORT_NETWORK, R.EQUITY_ATTRIBUTE),
                "Do not call a candidate site clinically qualified, staffed, supplied, or publicly accepted.",
            ),
            axis(
                D.ALLOCATE,
                "vaccines-tests-treatment",
                "Allocate vaccines, tests, treatment, and outreach",
                "How should constrained supplies and service capacity be allocated under clinical and equity priorities?",
                "infectious-disease prevention and treatment resources",
                "clinical-priority and minimum-access allocation",
                "eligible need without assigned service capacity",
                "person-courses",
                S.POPULATION_GROUP,
                (R.EQUITY_ATTRIBUTE, R.REAL_TIME_STATE, R.LEGAL_REGULATORY),
                "Do not report allocated doses or slots as administered treatment or health benefit.",
            ),
            axis(
                D.SCHEDULE,
                "clinic-lab-calendar",
                "Schedule clinics, laboratories, and outreach teams",
                "When should appointments, mobile services, laboratory batches, and outreach shifts operate?",
                "infectious-disease clinic, laboratory, and outreach schedule",
                "demand-, cold-chain-, and turnaround-constrained scheduling",
                "priority demand outside service and turnaround targets",
                "person-hours",
                S.NETWORK,
                (R.SERVICE_SCHEDULE, R.REAL_TIME_STATE, R.FACILITY_INVENTORY),
                "Do not call a schedule operated, appointments completed, or specimens processed.",
            ),
            axis(
                D.STRESS_TEST,
                "multi-pathogen-surge",
                "Stress-test public-health operations under multi-pathogen surge",
                "Which capacity strategy preserves essential surveillance, testing, care, and communication under correlated surge?",
                "infectious-disease operations under correlated surge",
                "multi-pathogen demand, workforce, supply, and facility failure simulation",
                "scenario-weighted unmet priority health-service demand",
                "encounters",
                S.NETWORK,
                (R.ASSET_CONDITION, R.REAL_TIME_STATE, R.FINANCIAL_COST),
                "Do not present synthetic pathogen or demand scenarios as epidemiological forecasts.",
            ),
            axis(
                D.EVALUATE,
                "outreach-access-effect",
                "Evaluate targeted infectious-disease access strategies",
                "Did phased mobile access and outreach improve verified service uptake without widening disparities?",
                "phased mobile infectious-disease service and outreach",
                "randomized encouragement or staggered access evaluation",
                "change in verified eligible service completion",
                "percentage points",
                S.POPULATION_GROUP,
                (R.EQUITY_ATTRIBUTE, R.COMMUNITY_INPUT),
                "Do not infer infection prevention or clinical benefit from appointment or uptake outcomes alone.",
            ),
        ),
    ),
    matrix_family(
        family_id="health.food-environment",
        suite=SUITE,
        title="Food access and environmental health",
        description=(
            "Eight decisions for service-gap diagnosis, inspection and assistance forecasting, prevention "
            "portfolios, access siting, inspection allocation, field schedules, disruption stress, and evaluation."
        ),
        affected_system="food access, environmental health inspection, and community protection",
        decision_owner="environmental health commissioner and food-access program director",
        common_source_roles=(R.GEOGRAPHIC_IDENTITY, R.DEMOGRAPHIC_CONTEXT, R.FACILITY_INVENTORY),
        common_assumptions=(
            "Food outlets, inspections, assistance, prices, access, and environmental complaints have separate semantics.",
            "Area food access is not treated as individual diet, food security, or health outcome.",
        ),
        transportability_risks=(
            "Retail markets, informal food systems, inspection law, mobility, prices, and eligibility vary.",
            "Administrative participation can understate eligible need.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "food-environment-gaps",
                "Diagnose food-access and environmental-health service gaps",
                "Where do outlet access, affordability, verified hazards, inspection coverage, and assistance gaps coincide?",
                "food-access and environmental-health service gaps",
                "retail-access, inspection, price, and service triangulation",
                "people in high-need low-service conditions",
                "people",
                S.NEIGHBORHOOD,
                (R.HOUSING_MARKET, R.MUNICIPAL_DEMAND, R.EQUITY_ATTRIBUTE),
                "Do not convert request labels, outlet distance, or program nonparticipation into verified hazard or hunger.",
            ),
            axis(
                D.FORECAST,
                "inspection-assistance-demand",
                "Forecast inspection and food-assistance service demand",
                "What seasonal inspection, complaint, market-disruption, and assistance workload should operations prepare for?",
                "environmental-health inspection and food-assistance demand",
                "seasonal event- and market-conditioned workload forecasting",
                "priority service demand above staffed capacity",
                "cases per week",
                S.SERVICE_AREA,
                (R.MUNICIPAL_DEMAND, R.OPERATING_CAPACITY, R.CLIMATE_HAZARD),
                "Do not call forecast cases verified violations, illness, or food insecurity.",
            ),
            axis(
                D.PRIORITIZE,
                "food-health-portfolio",
                "Prioritize food-access and environmental-health investments",
                "Which inspection, cold-chain, market, transportation, and assistance investments should be funded?",
                "food-access and environmental-health investment portfolio",
                "access-, risk-, equity-, and lifecycle portfolio optimization",
                "population-weighted food and environmental service gap",
                "person-days",
                S.ASSET,
                (R.FINANCIAL_COST, R.ASSET_CONDITION, R.EQUITY_ATTRIBUTE),
                "Do not report modeled access improvement as better diet, health, or verified hazard reduction.",
            ),
            axis(
                D.SITE,
                "food-access-services",
                "Site food-access and environmental-health service points",
                "Where should mobile markets, benefit navigation, cooling, and field-service access points operate?",
                "food-access and environmental-health service locations",
                "capacitated multi-service access location-allocation",
                "eligible people beyond affordable timely service access",
                "people",
                S.FACILITY,
                (R.LAND_PARCEL, R.TRANSPORT_NETWORK, R.EQUITY_ATTRIBUTE),
                "Do not label a site affordable, culturally appropriate, permitted, or used without evidence.",
            ),
            axis(
                D.ALLOCATE,
                "inspection-assistance-resources",
                "Allocate inspectors, food support, and field resources",
                "How should inspectors, sampling, emergency food, refrigeration, and navigation capacity be distributed?",
                "environmental-health inspection and food-support resources",
                "risk-tiered minimum-access resource allocation",
                "priority cases and eligible demand without assigned capacity",
                "cases",
                S.SERVICE_AREA,
                (R.OPERATING_CAPACITY, R.EQUITY_ATTRIBUTE, R.MUNICIPAL_DEMAND),
                "Do not report assigned inspections, benefits, or food supplies as completed or received.",
            ),
            axis(
                D.SCHEDULE,
                "inspection-mobile-service",
                "Schedule inspections and mobile food services",
                "When should risk-based inspections, follow-ups, mobile markets, and benefit navigation operate?",
                "environmental-health inspection and mobile food-service schedule",
                "risk-, travel-, perishability-, and capacity-constrained scheduling",
                "priority case-days outside response targets",
                "case-days",
                S.NETWORK,
                (R.SERVICE_SCHEDULE, R.OPERATING_CAPACITY, R.REAL_TIME_STATE),
                "Do not call a scheduled visit completed, a violation confirmed, or assistance received.",
            ),
            axis(
                D.STRESS_TEST,
                "food-system-disruption",
                "Stress-test food and environmental-health continuity",
                "Which response portfolio preserves safe food access during power, supply, climate, and facility disruptions?",
                "food-access and environmental-health continuity under disruption",
                "supply, cold-chain, facility, demand, and workforce failure simulation",
                "scenario-weighted people below minimum safe food access",
                "person-days",
                S.NETWORK,
                (R.CLIMATE_HAZARD, R.ASSET_CONDITION, R.OPERATING_CAPACITY),
                "Do not present synthetic shortages, contamination, or facility failures as observed events.",
            ),
            axis(
                D.EVALUATE,
                "mobile-food-access-effect",
                "Evaluate mobile food-access and benefit-navigation programs",
                "Did phased mobile services improve verified access and benefit completion among eligible groups?",
                "phased mobile food-access and benefit-navigation program",
                "staggered rollout evaluation with eligible-population panels",
                "change in verified affordable food-service completion",
                "percentage points",
                S.POPULATION_GROUP,
                (R.EQUITY_ATTRIBUTE, R.COMMUNITY_INPUT, R.HOUSING_MARKET),
                "Do not infer food security, diet quality, or health impact from program use alone.",
            ),
        ),
    ),
)

__all__ = ["HEALTH_FAMILIES"]
