"""Thirty-two housing, land-use, and regeneration decision designs."""

# ruff: noqa: E501 -- long policy statements are indivisible catalog content.

from civicdecision.deep.models import ApplicationSuite
from civicdecision.scenario_library.matrix import axis, matrix_family
from civicdecision.scenario_library.seeds import D, R, S

SUITE = ApplicationSuite.HOUSING_LAND_USE
BOUNDARY = (
    "Requests, listings, parcels, and administrative records do not alone verify conditions or need.",
    "Screened sites and portfolios are not permits, acquisitions, adopted plans, or completed housing.",
    "Displacement, affordability, habitability, and program effects require direct outcomes and identification.",
)


HOUSING_FAMILIES = (
    matrix_family(
        family_id="housing.habitability-code",
        suite=SUITE,
        title="Housing habitability and code operations",
        description=(
            "Eight decisions for condition-signal diagnosis, inspection forecasting, repair portfolios, "
            "service access, inspector allocation, case scheduling, surge stress, and enforcement evaluation."
        ),
        affected_system="housing inspection, code enforcement, repair, and tenant-support system",
        decision_owner="housing-code commissioner and tenant-protection director",
        common_source_roles=(R.MUNICIPAL_DEMAND, R.HOUSING_MARKET, R.GEOGRAPHIC_IDENTITY),
        common_assumptions=(
            "Complaints, inspections, violations, ownership, repair, and closure records retain distinct semantics.",
            "Tenant vulnerability and building condition are measured only from authorized, documented sources.",
        ),
        transportability_risks=(
            "Housing law, tenure, building age, complaint access, inspection practice, and enforcement differ.",
            "Complaint records may over- or under-represent physical conditions and retaliation risk.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "habitability-signals",
                "Diagnose unresolved housing habitability signals",
                "Which buildings show persistent complaint, inspection, violation, ownership, and repair patterns requiring verification?",
                "building-level unresolved habitability signals",
                "longitudinal complaint-inspection-repair reconciliation",
                "high-priority buildings with unresolved verified conditions",
                "buildings",
                S.ASSET,
                (R.ASSET_CONDITION, R.LAND_PARCEL, R.EQUITY_ATTRIBUTE),
                "Do not label complaint keywords as verified violations, unsafe housing, or landlord misconduct.",
            ),
            axis(
                D.FORECAST,
                "inspection-repair-demand",
                "Forecast housing inspection and emergency-repair demand",
                "What seasonal inspection, follow-up, relocation, and emergency-repair workload should operations prepare for?",
                "housing inspection and emergency-repair workload",
                "building-history and weather-conditioned case forecasting",
                "priority cases above verified response capacity",
                "cases per week",
                S.SERVICE_AREA,
                (R.ASSET_CONDITION, R.OPERATING_CAPACITY, R.CLIMATE_HAZARD),
                "Do not call forecast cases verified violations, displaced households, or completed repairs.",
            ),
            axis(
                D.PRIORITIZE,
                "habitability-interventions",
                "Prioritize habitability inspection and repair interventions",
                "Which inspection, legal support, emergency repair, and rehabilitation cases should receive limited resources?",
                "housing habitability intervention portfolio",
                "severity-, vulnerability-, evidence-, and deliverability-weighted prioritization",
                "verified severe condition-days unresolved",
                "building-days",
                S.ASSET,
                (R.ASSET_CONDITION, R.FINANCIAL_COST, R.EQUITY_ATTRIBUTE),
                "Do not report ranked complaints as adjudicated violations or modeled repairs as completed.",
                existing_template_ref="deep.housing.request-triage.v1",
            ),
            axis(
                D.SITE,
                "tenant-service-access",
                "Site tenant-support and emergency housing access points",
                "Where should multilingual inspection intake, legal navigation, repair, and temporary housing services operate?",
                "tenant-support and emergency housing service locations",
                "need-, language-, transit-, and capacity-aware service siting",
                "at-risk tenants beyond timely qualified support",
                "households",
                S.FACILITY,
                (R.FACILITY_INVENTORY, R.TRANSPORT_NETWORK, R.EQUITY_ATTRIBUTE),
                "Do not call a candidate site legally qualified, accessible, trusted, or used.",
            ),
            axis(
                D.ALLOCATE,
                "inspectors-repair-support",
                "Allocate housing inspectors and emergency repair support",
                "How should inspectors, language access, legal navigation, repair grants, and relocation capacity be assigned?",
                "housing inspection, repair, and tenant-protection resources",
                "severity and minimum-service constrained case allocation",
                "verified priority households without assigned response capacity",
                "households",
                S.SERVICE_AREA,
                (R.OPERATING_CAPACITY, R.EQUITY_ATTRIBUTE, R.LEGAL_REGULATORY),
                "Do not report an assignment as inspection, repair, legal resolution, or safe relocation.",
            ),
            axis(
                D.SCHEDULE,
                "inspection-enforcement-calendar",
                "Schedule housing inspections, follow-ups, and repairs",
                "When should initial inspections, rechecks, legal notices, repairs, and tenant support occur?",
                "housing inspection, enforcement, and repair schedule",
                "severity-, dependency-, and statutory-deadline scheduling",
                "priority case-days beyond lawful response deadlines",
                "case-days",
                S.ASSET,
                (R.SERVICE_SCHEDULE, R.OPERATING_CAPACITY, R.LEGAL_REGULATORY),
                "Do not infer completed inspection, notice, repair, or safe occupancy from a scheduled task.",
            ),
            axis(
                D.STRESS_TEST,
                "housing-emergency-surge",
                "Stress-test housing response during extreme-condition surges",
                "Which plan preserves inspection, repair, shelter, and tenant support during heat, cold, flood, or outage surges?",
                "housing habitability response under extreme-condition surge",
                "case, facility, contractor, and relocation-capacity failure simulation",
                "scenario-weighted priority households without timely protection",
                "household-days",
                S.NETWORK,
                (R.CLIMATE_HAZARD, R.FACILITY_INVENTORY, R.OPERATING_CAPACITY),
                "Do not present synthetic conditions or households as observed violations or displacement.",
            ),
            axis(
                D.EVALUATE,
                "proactive-inspection-effect",
                "Evaluate proactive housing inspection and repair support",
                "Did phased proactive inspection reduce verified severe conditions without displacement or selective enforcement?",
                "phased proactive inspection and repair-support program",
                "staggered building-level evaluation with tenant outcome panels",
                "change in verified severe condition duration",
                "days per building",
                S.ASSET,
                (R.ASSET_CONDITION, R.EQUITY_ATTRIBUTE, R.LEGAL_REGULATORY),
                "Do not infer causal habitability, health, or displacement effects from complaint closure alone.",
            ),
        ),
    ),
    matrix_family(
        family_id="housing.homelessness-prevention",
        suite=SUITE,
        title="Homelessness prevention and housing stability",
        description=(
            "Eight decisions for instability diagnosis, service-demand forecasting, prevention portfolios, "
            "access siting, assistance allocation, case scheduling, surge stress, and program evaluation."
        ),
        affected_system="housing-stability, eviction prevention, shelter diversion, and support coordination",
        decision_owner="homelessness response director and housing-stability administrator",
        common_source_roles=(R.HOUSING_MARKET, R.DEMOGRAPHIC_CONTEXT, R.OPERATING_CAPACITY),
        common_assumptions=(
            "Court, assistance, shelter, outreach, housing, and service records use privacy-preserving linkage.",
            "Risk models support outreach only and never determine legal rights or automatic denial.",
        ),
        transportability_risks=(
            "Eviction law, rents, benefits, shelter systems, informal displacement, and data linkage differ.",
            "Administrative records omit people who do not seek or cannot access services.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "stability-service-gaps",
                "Diagnose housing-instability and prevention-service gaps",
                "Where do rent burden, court filings, shelter entry, benefit loss, and service access reveal preventable system gaps?",
                "housing-instability pathways and prevention-service gaps",
                "privacy-preserving longitudinal pathway diagnosis",
                "eligible households entering crisis without prior prevention access",
                "households",
                S.POPULATION_GROUP,
                (R.OUTCOME_PANEL, R.EQUITY_ATTRIBUTE, R.COMMUNITY_INPUT),
                "Do not label a household homeless, likely to be evicted, or noncompliant from proxy variables.",
            ),
            axis(
                D.FORECAST,
                "prevention-service-demand",
                "Forecast housing-stability service demand",
                "What range of legal, rental, diversion, outreach, and shelter demand should the system prepare for?",
                "housing-stability and homelessness-prevention demand",
                "market, court, season, and service-flow forecasting",
                "priority household demand above prevention capacity",
                "households per month",
                S.SERVICE_AREA,
                (R.REAL_TIME_STATE, R.SERVICE_SCHEDULE, R.MUNICIPAL_DEMAND),
                "Do not call forecast service demand evictions, homelessness entries, or individual risk.",
            ),
            axis(
                D.PRIORITIZE,
                "stability-program-portfolio",
                "Prioritize housing-stability prevention programs",
                "Which legal aid, rental support, mediation, navigation, and diversion measures should be expanded?",
                "housing-stability prevention program portfolio",
                "outcome-, equity-, cost-, and capacity-aware program prioritization",
                "expected unresolved housing-stability crises",
                "household episodes",
                S.SERVICE_AREA,
                (R.FINANCIAL_COST, R.OUTCOME_PANEL, R.EQUITY_ATTRIBUTE),
                "Do not report modeled crisis reduction as prevented eviction or homelessness.",
            ),
            axis(
                D.SITE,
                "stability-access-hubs",
                "Site low-barrier housing-stability access hubs",
                "Where should legal, benefits, diversion, document, and housing-navigation services be co-located?",
                "low-barrier housing-stability service hubs",
                "need-, transit-, language-, privacy-, and capacity-aware hub siting",
                "eligible households beyond timely prevention access",
                "households",
                S.FACILITY,
                (R.FACILITY_INVENTORY, R.TRANSPORT_NETWORK, R.EQUITY_ATTRIBUTE),
                "Do not call a candidate site trusted, low-barrier, accessible, or effective without user evidence.",
            ),
            axis(
                D.ALLOCATE,
                "prevention-assistance",
                "Allocate rental, legal, diversion, and navigation assistance",
                "How should limited flexible funds, legal capacity, shelter diversion, and case navigation be assigned?",
                "housing-stability prevention assistance",
                "rights-preserving eligibility and minimum-service allocation",
                "eligible urgent households without assigned assistance",
                "households",
                S.POPULATION_GROUP,
                (R.EQUITY_ATTRIBUTE, R.LEGAL_REGULATORY, R.REAL_TIME_STATE),
                "Do not report allocated funds or case capacity as received assistance or stable housing.",
            ),
            axis(
                D.SCHEDULE,
                "prevention-caseflow",
                "Schedule prevention casework and legal deadlines",
                "When should intake, document recovery, legal action, payment, mediation, and follow-up occur?",
                "housing-stability prevention caseflow schedule",
                "deadline-, dependency-, and urgency-aware case scheduling",
                "urgent household-days beyond actionable deadlines",
                "household-days",
                S.SERVICE_AREA,
                (R.SERVICE_SCHEDULE, R.LEGAL_REGULATORY, R.REAL_TIME_STATE),
                "Do not call scheduled case actions completed, legally sufficient, or successful.",
            ),
            axis(
                D.STRESS_TEST,
                "housing-stability-surge",
                "Stress-test housing-stability capacity under market shock",
                "Which prevention strategy preserves minimum support during rent, income, disaster, and shelter-capacity shocks?",
                "housing-stability prevention under compound market shock",
                "household-flow, funding, legal, and shelter-capacity simulation",
                "scenario-weighted urgent households without timely prevention",
                "households",
                S.NETWORK,
                (R.FINANCIAL_COST, R.FACILITY_INVENTORY, R.CLIMATE_HAZARD),
                "Do not present synthetic housing shocks or household pathways as forecasts or observed crises.",
            ),
            axis(
                D.EVALUATE,
                "rental-assistance-effect",
                "Evaluate rental assistance and legal support",
                "Did phased prevention support improve verified housing stability without exclusion or delayed harm?",
                "phased rental assistance and legal-support program",
                "randomized lottery or quasi-random eligibility evaluation",
                "change in verified stable housing retention",
                "percentage points",
                S.POPULATION_GROUP,
                (R.EQUITY_ATTRIBUTE, R.LEGAL_REGULATORY, R.COMMUNITY_INPUT),
                "Do not infer long-term stability, well-being, or causal impact from payment issuance alone.",
            ),
        ),
    ),
    matrix_family(
        family_id="housing.affordable-supply",
        suite=SUITE,
        title="Affordable housing siting and preservation",
        description=(
            "Eight decisions for supply-risk diagnosis, pipeline forecasting, preservation portfolios, "
            "new site selection, subsidy allocation, development scheduling, financing stress, and evaluation."
        ),
        affected_system="affordable housing production, preservation, subsidy, and compliance system",
        decision_owner="housing development commissioner and affordable-housing finance director",
        common_source_roles=(R.HOUSING_MARKET, R.LAND_PARCEL, R.GEOGRAPHIC_IDENTITY),
        common_assumptions=(
            "Units, affordability restrictions, occupancy, financing, condition, pipeline, and parcel feasibility are reconciled.",
            "Modeled development feasibility is not treated as entitlement, financing close, or completed housing.",
        ),
        transportability_risks=(
            "Land law, subsidy programs, construction costs, finance, tenant protections, and markets differ.",
            "Observed transactions may omit informal displacement and off-market preservation risks.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "affordability-loss-risk",
                "Diagnose affordable-housing loss and supply gaps",
                "Which properties, restrictions, market pressures, conditions, and access patterns indicate preservation or supply risk?",
                "affordable-housing preservation risk and supply gaps",
                "property-level restriction, condition, finance, and market reconciliation",
                "affordable homes at verified near-term loss risk",
                "homes",
                S.PARCEL,
                (R.ASSET_CONDITION, R.FINANCIAL_COST, R.EQUITY_ATTRIBUTE),
                "Do not label market pressure displacement or a unit affordable without restriction and rent evidence.",
            ),
            axis(
                D.FORECAST,
                "affordable-pipeline",
                "Forecast affordable-housing pipeline and preservation need",
                "What probabilistic completion, expiry, cost, and unit-loss range should housing operations plan around?",
                "affordable-housing pipeline and preservation demand",
                "project-stage survival and restriction-expiry forecasting",
                "net affordable homes below adopted supply targets",
                "homes",
                S.CITYWIDE,
                (R.FINANCIAL_COST, R.REAL_TIME_STATE, R.LEGAL_REGULATORY),
                "Do not count proposed, permitted, or financed units as completed occupied homes.",
            ),
            axis(
                D.PRIORITIZE,
                "preservation-development-portfolio",
                "Prioritize affordable-housing preservation and development",
                "Which preservation, acquisition, rehabilitation, and new-development projects should receive funding?",
                "affordable-housing preservation and development portfolio",
                "unit-year, equity, access, risk, and subsidy portfolio optimization",
                "affordable home-years lost relative to targets",
                "home-years",
                S.PARCEL,
                (R.ASSET_CONDITION, R.FINANCIAL_COST, R.EQUITY_ATTRIBUTE),
                "Do not report selected projects as financed, constructed, occupied, or preserved.",
            ),
            axis(
                D.SITE,
                "affordable-housing-sites",
                "Site affordable housing with access and anti-displacement safeguards",
                "Which parcels support feasible affordable homes near opportunity while avoiding hazard and displacement burdens?",
                "affordable-housing development locations",
                "parcel feasibility, access, hazard, and displacement-aware siting",
                "feasible affordable homes outside opportunity access",
                "homes",
                S.PARCEL,
                (R.TRANSPORT_NETWORK, R.LEGAL_REGULATORY, R.CLIMATE_HAZARD, R.EQUITY_ATTRIBUTE),
                "Do not call a screened parcel entitled, acquired, financeable, buildable, or community-supported.",
            ),
            axis(
                D.ALLOCATE,
                "housing-subsidy",
                "Allocate housing subsidy and preservation capacity",
                "How should tax credits, loans, grants, vouchers, and technical capacity be allocated?",
                "affordable-housing subsidy and delivery capacity",
                "affordability-duration, need, leverage, and equity allocation",
                "eligible affordable home-years without assigned subsidy",
                "home-years",
                S.PARCEL,
                (R.FINANCIAL_COST, R.EQUITY_ATTRIBUTE, R.OPERATING_CAPACITY),
                "Do not report a modeled subsidy allocation as an award, closing, or completed home.",
            ),
            axis(
                D.SCHEDULE,
                "housing-pipeline-sequence",
                "Schedule affordable-housing pipeline and preservation actions",
                "When should acquisition, resident protection, design, entitlement, finance, construction, and compliance actions occur?",
                "affordable-housing project and preservation schedule",
                "dependency-, expiry-, relocation-, and financing-window scheduling",
                "affordable home-years lost to avoidable project delay",
                "home-years",
                S.PARCEL,
                (R.SERVICE_SCHEDULE, R.LEGAL_REGULATORY, R.FINANCIAL_COST),
                "Do not call a project schedule approved, financed, under construction, or complete.",
            ),
            axis(
                D.STRESS_TEST,
                "housing-finance-shock",
                "Stress-test affordable-housing delivery under finance and cost shocks",
                "Which preservation and production strategy sustains affordability across rate, cost, subsidy, and market shocks?",
                "affordable-housing portfolio under financing and delivery shock",
                "project-level finance, cost, delay, and attrition simulation",
                "scenario-weighted affordable home-years not delivered or preserved",
                "home-years",
                S.CITYWIDE,
                (R.FINANCIAL_COST, R.OPERATING_CAPACITY, R.ASSET_CONDITION),
                "Do not present synthetic financing failures or modeled units as observed outcomes.",
            ),
            axis(
                D.EVALUATE,
                "preservation-program-effect",
                "Evaluate affordable-housing preservation interventions",
                "Did phased acquisition or rehabilitation preserve verified affordability and housing stability?",
                "phased affordable-housing acquisition and rehabilitation",
                "matched property event-study with tenant and restriction panels",
                "change in verified affordable home-years and tenant retention",
                "home-years and percentage points",
                S.PARCEL,
                (R.EQUITY_ATTRIBUTE, R.ASSET_CONDITION, R.LEGAL_REGULATORY),
                "Do not infer causal anti-displacement or well-being effects from project completion alone.",
            ),
        ),
    ),
    matrix_family(
        family_id="housing.land-use-regeneration",
        suite=SUITE,
        title="Land use, regeneration, and neighborhood change",
        description=(
            "Eight decisions for land diagnosis, development forecasting, public investment portfolios, "
            "facility siting, benefit allocation, phasing, market stress, and regeneration evaluation."
        ),
        affected_system="land-use planning, public investment, regeneration, and community-benefit system",
        decision_owner="planning director and neighborhood regeneration commissioner",
        common_source_roles=(R.LAND_PARCEL, R.HOUSING_MARKET, R.GEOGRAPHIC_IDENTITY),
        common_assumptions=(
            "Parcels, zoning, ownership, development, business, housing, public assets, and population use dated versions.",
            "Scenario capacity and market response are not treated as approved projects or inevitable change.",
        ),
        transportability_risks=(
            "Planning law, property rights, finance, markets, institutions, and community priorities differ.",
            "Parcel and transaction data may miss informal tenure, businesses, and cultural assets.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "land-use-friction",
                "Diagnose land-use capacity, vacancy, and community-asset friction",
                "Where do parcel constraints, vacancy, infrastructure, hazards, market pressure, and valued assets create planning conflicts?",
                "parcel-level regeneration opportunities and community risks",
                "zoning, parcel, infrastructure, market, and community-asset diagnosis",
                "priority parcels with unresolved feasibility and community-risk conflicts",
                "parcels",
                S.PARCEL,
                (R.ASSET_INVENTORY, R.CLIMATE_HAZARD, R.COMMUNITY_INPUT),
                "Do not label vacancy blight, development capacity, consent, or regeneration opportunity without verification.",
            ),
            axis(
                D.FORECAST,
                "development-displacement",
                "Forecast development, affordability, and displacement pressure",
                "What range of land use, prices, development, tenure, and business change follows each policy scenario?",
                "neighborhood development and displacement pressure",
                "scenario-conditioned parcel and housing-market forecasting",
                "residents and businesses exposed to modeled involuntary displacement pressure",
                "households and establishments",
                S.NEIGHBORHOOD,
                (R.EQUITY_ATTRIBUTE, R.FINANCIAL_COST, R.OUTCOME_PANEL),
                "Do not present market scenarios as inevitable development or individual displacement predictions.",
            ),
            axis(
                D.PRIORITIZE,
                "regeneration-investments",
                "Prioritize inclusive regeneration investments",
                "Which infrastructure, public realm, housing, business, and cultural-asset investments should be sequenced?",
                "inclusive neighborhood regeneration investment portfolio",
                "community-benefit, access, risk, and lifecycle portfolio optimization",
                "unmet verified community-benefit and infrastructure need",
                "benefit-units",
                S.ASSET,
                (R.ASSET_CONDITION, R.FINANCIAL_COST, R.COMMUNITY_INPUT),
                "Do not report modeled community benefits as agreed, delivered, or causally achieved.",
            ),
            axis(
                D.SITE,
                "community-anchor-sites",
                "Site public anchors and mixed-use regeneration projects",
                "Which parcels can support public anchors and mixed use while protecting access, heritage, affordability, and climate safety?",
                "public anchor and mixed-use regeneration locations",
                "parcel, access, heritage, hazard, and community-goal siting",
                "verified service and opportunity need beyond feasible anchor access",
                "people",
                S.PARCEL,
                (R.TRANSPORT_NETWORK, R.LEGAL_REGULATORY, R.CLIMATE_HAZARD, R.COMMUNITY_INPUT),
                "Do not call a screened parcel approved, acquired, financeable, consented, or beneficial.",
            ),
            axis(
                D.ALLOCATE,
                "regeneration-benefits",
                "Allocate regeneration funds and community benefits",
                "How should capital, land value, grants, affordable space, jobs, and public benefits be distributed?",
                "regeneration funding and enforceable community benefits",
                "minimum-benefit, need, deliverability, and displacement-risk allocation",
                "verified community priorities without funded enforceable benefit",
                "priority units",
                S.NEIGHBORHOOD,
                (R.FINANCIAL_COST, R.EQUITY_ATTRIBUTE, R.COMMUNITY_INPUT, R.LEGAL_REGULATORY),
                "Do not present modeled allocations as negotiated, legally secured, funded, or delivered benefits.",
            ),
            axis(
                D.SCHEDULE,
                "regeneration-phasing",
                "Schedule regeneration infrastructure and protections",
                "When should tenant protections, infrastructure, affordable space, construction, and public assets be delivered?",
                "regeneration project and community-protection phasing",
                "dependency and no-net-harm milestone scheduling",
                "resident- and business-days exposed before required protections",
                "person-days",
                S.NEIGHBORHOOD,
                (R.SERVICE_SCHEDULE, R.LEGAL_REGULATORY, R.FINANCIAL_COST),
                "Do not call a proposed phase funded, permitted, contractually secured, or completed.",
            ),
            axis(
                D.STRESS_TEST,
                "regeneration-market-shock",
                "Stress-test regeneration under market and delivery shocks",
                "Which plan preserves affordability and public benefits across cost, finance, demand, delay, and climate shocks?",
                "inclusive regeneration plan under market and delivery shock",
                "parcel, finance, displacement, infrastructure, and hazard simulation",
                "scenario-weighted loss of protected housing, businesses, and public benefits",
                "protected-unit years",
                S.NEIGHBORHOOD,
                (R.FINANCIAL_COST, R.CLIMATE_HAZARD, R.OPERATING_CAPACITY),
                "Do not present synthetic market paths as forecasts or modeled protections as secured rights.",
            ),
            axis(
                D.EVALUATE,
                "regeneration-effect",
                "Evaluate regeneration and community-benefit effects",
                "Did phased regeneration improve verified access and opportunity without displacement or benefit leakage?",
                "phased regeneration and community-benefit intervention",
                "matched neighborhood event-study with resident and business panels",
                "change in verified access, stability, and secured community benefits",
                "standardized outcome index",
                S.NEIGHBORHOOD,
                (R.EQUITY_ATTRIBUTE, R.COMMUNITY_INPUT, R.LEGAL_REGULATORY),
                "Do not infer inclusive growth, well-being, or anti-displacement effects from investment totals alone.",
            ),
        ),
    ),
)

__all__ = ["HOUSING_FAMILIES"]
