"""Thirty-two infrastructure, asset-risk, energy, and finance decision designs."""

# ruff: noqa: E501 -- long policy statements are indivisible catalog content.

from civicdecision.deep.models import ApplicationSuite
from civicdecision.scenario_library.matrix import axis, matrix_family
from civicdecision.scenario_library.seeds import D, R, S

SUITE = ApplicationSuite.INFRASTRUCTURE_FINANCE
BOUNDARY = (
    "Requests and proxy indicators do not replace engineering inspection, accounting, or legal review.",
    "Selected projects and schedules are planning outputs, not appropriations, designs, contracts, or construction.",
    "Modeled lifecycle, emissions, reliability, and fiscal effects are not realized outcomes.",
)


INFRASTRUCTURE_FAMILIES = (
    matrix_family(
        family_id="infrastructure.roads-bridges",
        suite=SUITE,
        title="Road and bridge asset management",
        description=(
            "Eight decisions for condition diagnosis, failure forecasting, maintenance portfolios, depot "
            "siting, crew allocation, work scheduling, network stress, and treatment evaluation."
        ),
        affected_system="roadway, bridge, sidewalk, signal, and public right-of-way asset network",
        decision_owner="public works asset manager and chief infrastructure engineer",
        common_source_roles=(R.ASSET_INVENTORY, R.ASSET_CONDITION, R.GEOGRAPHIC_IDENTITY),
        common_assumptions=(
            "Assets, inspections, defects, work orders, costs, traffic, restrictions, and completion are reconciled.",
            "Engineering thresholds and deterioration models are locally reviewed and versioned.",
        ),
        transportability_risks=(
            "Materials, climate, loading, standards, inspection, procurement, and unit costs differ.",
            "Service requests can reveal workload but not structural condition or safety.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "asset-condition-failure",
                "Diagnose roadway and bridge condition and failure patterns",
                "Which inspected assets show verified deterioration, repeated defects, dependency risk, or data inconsistency?",
                "road and bridge condition and failure patterns",
                "inspection, sensor, work-order, request, and dependency reconciliation",
                "high-consequence assets with unresolved verified defects",
                "assets",
                S.ASSET,
                (R.MUNICIPAL_DEMAND, R.REAL_TIME_STATE, R.TRANSPORT_NETWORK),
                "Do not convert infrastructure request labels into engineering condition or safety findings.",
            ),
            axis(
                D.FORECAST,
                "asset-deterioration",
                "Forecast road and bridge deterioration and work demand",
                "What probabilistic condition, defect, restriction, and maintenance workload should asset managers prepare for?",
                "road and bridge deterioration and maintenance demand",
                "inspection-history, load, climate, and treatment-conditioned forecasting",
                "lane- and asset-days below condition targets",
                "asset-days",
                S.ASSET,
                (R.CLIMATE_HAZARD, R.TRANSPORT_NETWORK, R.OPERATING_CAPACITY),
                "Do not present modeled deterioration as an inspection, failure, closure, or safety prediction.",
            ),
            axis(
                D.PRIORITIZE,
                "maintenance-renewal",
                "Prioritize road and bridge maintenance and renewal",
                "Which preventive, rehabilitative, safety, accessibility, and replacement projects should be funded?",
                "road and bridge maintenance and renewal portfolio",
                "condition, consequence, access, lifecycle cost, and deliverability optimization",
                "expected risk-adjusted deficient asset-years",
                "asset-years",
                S.ASSET,
                (R.FINANCIAL_COST, R.TRANSPORT_NETWORK, R.EQUITY_ATTRIBUTE),
                "Do not report request-based prioritization as engineering design, capital approval, or completed work.",
                existing_template_ref="deep.infrastructure.maintenance-portfolio.v1",
            ),
            axis(
                D.SITE,
                "maintenance-depots",
                "Site maintenance depots and material staging",
                "Where should depots, materials, equipment, and emergency staging improve resilient network coverage?",
                "road and bridge maintenance depot and staging locations",
                "network coverage, hazard, parcel, and burden-aware facility siting",
                "high-consequence assets beyond feasible maintenance response",
                "assets",
                S.FACILITY,
                (R.LAND_PARCEL, R.TRANSPORT_NETWORK, R.CLIMATE_HAZARD, R.EQUITY_ATTRIBUTE),
                "Do not call a candidate depot permitted, safe, acquired, accepted, or operational.",
            ),
            axis(
                D.ALLOCATE,
                "maintenance-crews-equipment",
                "Allocate maintenance crews, equipment, and materials",
                "How should qualified crews, specialty equipment, materials, and inspection capacity be assigned?",
                "road and bridge maintenance resources",
                "risk-, skill-, network-, and minimum-service allocation",
                "high-consequence work without assigned qualified capacity",
                "work orders",
                S.NETWORK,
                (R.OPERATING_CAPACITY, R.REAL_TIME_STATE, R.EQUITY_ATTRIBUTE),
                "Do not report assigned resources as inspected, repaired, reopened, or safe assets.",
            ),
            axis(
                D.SCHEDULE,
                "maintenance-construction",
                "Schedule inspections, maintenance, and construction windows",
                "When should inspections and treatments occur given condition, traffic, weather, dependencies, and permits?",
                "road and bridge inspection and maintenance schedule",
                "condition-, dependency-, traffic-, weather-, and crew-aware scheduling",
                "high-consequence asset-days beyond treatment thresholds",
                "asset-days",
                S.NETWORK,
                (R.SERVICE_SCHEDULE, R.TRANSPORT_NETWORK, R.CLIMATE_HAZARD),
                "Do not call a scheduled inspection or treatment completed or the asset safe.",
            ),
            axis(
                D.STRESS_TEST,
                "transport-asset-failure",
                "Stress-test transport infrastructure under compound failure",
                "Which maintenance and continuity strategy preserves essential access under asset, hazard, supply, and crew failures?",
                "road and bridge network continuity under compound failure",
                "asset deterioration, network closure, material, workforce, and hazard simulation",
                "scenario-weighted essential trips disconnected",
                "origin-destination pairs",
                S.NETWORK,
                (R.TRANSPORT_NETWORK, R.CLIMATE_HAZARD, R.OPERATING_CAPACITY),
                "Do not present synthetic defects, closures, or disconnected trips as observed events.",
            ),
            axis(
                D.EVALUATE,
                "preventive-maintenance-effect",
                "Evaluate preventive maintenance and treatment strategies",
                "Did phased preventive treatments extend verified asset condition and reduce unplanned service loss?",
                "phased road and bridge preventive maintenance treatment",
                "matched asset event-study with inspection and traffic panels",
                "change in verified condition life and unplanned restriction days",
                "asset-years and days",
                S.ASSET,
                (R.TRANSPORT_NETWORK, R.FINANCIAL_COST, R.REAL_TIME_STATE),
                "Do not infer structural safety or causal lifecycle value without comparable inspections and treatment assignment.",
            ),
        ),
    ),
    matrix_family(
        family_id="infrastructure.water-wastewater",
        suite=SUITE,
        title="Water and wastewater infrastructure",
        description=(
            "Eight decisions for failure diagnosis, demand forecasting, renewal portfolios, facility "
            "siting, repair allocation, maintenance scheduling, continuity stress, and renewal evaluation."
        ),
        affected_system="drinking-water distribution, sewer collection, pumping, and treatment assets",
        decision_owner="water and wastewater utility asset director",
        common_source_roles=(R.ASSET_INVENTORY, R.ASSET_CONDITION, R.GEOGRAPHIC_IDENTITY),
        common_assumptions=(
            "Assets, inspections, breaks, overflows, pressure, flow, quality, work, and complaints remain distinct.",
            "Hydraulic, process, condition, and consequence models receive utility engineering review.",
        ),
        transportability_risks=(
            "Network age, materials, soils, climate, regulation, treatment, hydraulics, and costs differ.",
            "Published incidents and complaints can omit failures or lack asset-level linkage.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "utility-failure-patterns",
                "Diagnose water and wastewater asset failure patterns",
                "Which assets show verified break, overflow, pressure, quality, condition, or repeat-repair patterns?",
                "water and wastewater asset failure patterns",
                "network-linked incident, sensor, inspection, laboratory, and work diagnosis",
                "high-consequence assets with unresolved failure evidence",
                "assets",
                S.NETWORK,
                (R.ENVIRONMENTAL_EXPOSURE, R.REAL_TIME_STATE, R.MUNICIPAL_DEMAND),
                "Do not infer water quality, leakage, overflow, or asset failure from complaints alone.",
            ),
            axis(
                D.FORECAST,
                "utility-demand-failures",
                "Forecast utility demand, failures, and treatment load",
                "What probabilistic flow, quality, break, overflow, and treatment-load range should operations prepare for?",
                "water and wastewater demand, failure, and treatment load",
                "weather, condition, hydraulic, and process-load forecasting",
                "service demand and failure load above operable capacity",
                "service-events per day",
                S.NETWORK,
                (R.CLIMATE_HAZARD, R.OPERATING_CAPACITY, R.REAL_TIME_STATE),
                "Do not present modeled breaks, quality events, or overflows as observed incidents.",
            ),
            axis(
                D.PRIORITIZE,
                "utility-renewal",
                "Prioritize water and wastewater renewal",
                "Which pipes, pumps, plants, storage, sensors, and process upgrades should enter the capital portfolio?",
                "water and wastewater renewal portfolio",
                "condition, consequence, compliance, equity, and lifecycle optimization",
                "expected risk-adjusted service interruption and compliance burden",
                "service-hours",
                S.ASSET,
                (R.FINANCIAL_COST, R.ENVIRONMENTAL_EXPOSURE, R.EQUITY_ATTRIBUTE),
                "Do not report modeled risk reduction as completed renewal, compliance, or avoided incidents.",
            ),
            axis(
                D.SITE,
                "utility-facilities",
                "Site utility storage, pumping, treatment, and recovery facilities",
                "Where should new facilities satisfy hydraulic need while limiting hazard and community burdens?",
                "water and wastewater facility locations",
                "hydraulic, parcel, hazard, environmental, and burden-aware siting",
                "critical service demand beyond resilient facility capacity",
                "service-units",
                S.FACILITY,
                (R.LAND_PARCEL, R.CLIMATE_HAZARD, R.LEGAL_REGULATORY, R.EQUITY_ATTRIBUTE),
                "Do not call a screened utility site permitted, engineered, acquired, safe, or accepted.",
            ),
            axis(
                D.ALLOCATE,
                "utility-repair-capacity",
                "Allocate utility repair, inspection, and emergency capacity",
                "How should qualified crews, laboratory capacity, bypass equipment, parts, and inspectors be assigned?",
                "water and wastewater repair and emergency resources",
                "consequence-, skill-, time-, and minimum-service allocation",
                "critical utility work without assigned qualified capacity",
                "work orders",
                S.NETWORK,
                (R.OPERATING_CAPACITY, R.REAL_TIME_STATE, R.ENVIRONMENTAL_EXPOSURE),
                "Do not report an assignment as repair, sampling, restored service, or compliance.",
            ),
            axis(
                D.SCHEDULE,
                "utility-maintenance",
                "Schedule utility inspection, maintenance, and renewal",
                "When should isolation, inspection, cleaning, repair, renewal, sampling, and process work occur?",
                "water and wastewater maintenance and renewal schedule",
                "condition, hydraulic, permit, dependency, and crew scheduling",
                "critical asset-days beyond maintenance and compliance windows",
                "asset-days",
                S.NETWORK,
                (R.SERVICE_SCHEDULE, R.LEGAL_REGULATORY, R.OPERATING_CAPACITY),
                "Do not call scheduled utility work complete, compliant, or safe.",
            ),
            axis(
                D.STRESS_TEST,
                "utility-continuity",
                "Stress-test water and wastewater continuity",
                "Which renewal and operations strategy preserves essential service under drought, flood, outage, contamination, and asset failure?",
                "water and wastewater continuity under compound disruption",
                "hydraulic, process, quality, power, asset, and workforce failure simulation",
                "scenario-weighted essential service interruption",
                "customer-hours",
                S.NETWORK,
                (R.CLIMATE_HAZARD, R.OPERATING_CAPACITY, R.ENVIRONMENTAL_EXPOSURE),
                "Do not present synthetic contamination, failure, or service interruption as observed.",
            ),
            axis(
                D.EVALUATE,
                "renewal-strategy-effect",
                "Evaluate utility renewal and pressure-management strategies",
                "Did phased renewal or pressure management reduce verified failures and service loss?",
                "phased utility renewal and pressure-management intervention",
                "matched asset event-study with hydraulic and work panels",
                "change in verified failures and service interruption",
                "events and customer-hours per asset-year",
                S.ASSET,
                (R.REAL_TIME_STATE, R.FINANCIAL_COST, R.ENVIRONMENTAL_EXPOSURE),
                "Do not infer causal water quality, health, or lifecycle effects from work completion alone.",
            ),
        ),
    ),
    matrix_family(
        family_id="infrastructure.energy-buildings",
        suite=SUITE,
        title="Municipal energy and building decarbonization",
        description=(
            "Eight decisions for energy diagnosis, load forecasting, retrofit portfolios, clean-energy "
            "siting, capital allocation, project scheduling, grid stress, and retrofit evaluation."
        ),
        affected_system="municipal buildings, distributed energy, electrification, and emissions management",
        decision_owner="municipal energy director and public-building portfolio manager",
        common_source_roles=(R.ASSET_INVENTORY, R.ENVIRONMENTAL_EXPOSURE, R.FINANCIAL_COST),
        common_assumptions=(
            "Meters, fuels, tariffs, weather, occupancy, equipment, projects, and emissions factors are versioned.",
            "Modeled energy and carbon savings remain distinct from measured post-project performance.",
        ),
        transportability_risks=(
            "Climate, grids, tariffs, fuels, building codes, stock, occupancy, and finance differ.",
            "Operational changes can confound retrofit performance comparisons.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "building-energy-performance",
                "Diagnose municipal building energy and emissions performance",
                "Which buildings show weather- and occupancy-adjusted energy, comfort, equipment, or emissions anomalies?",
                "municipal building energy, comfort, and emissions anomalies",
                "meter, weather, occupancy, equipment, and work-order reconciliation",
                "verified excess energy and emissions above building baselines",
                "megawatt-hours and tonnes CO2e",
                S.ASSET,
                (R.ASSET_CONDITION, R.OPERATING_CAPACITY, R.REAL_TIME_STATE),
                "Do not label benchmark deviation waste, malfunction, discomfort, or avoidable emissions without verification.",
            ),
            axis(
                D.FORECAST,
                "building-load-emissions",
                "Forecast municipal building load, cost, and emissions",
                "What interval of electric, thermal, peak, cost, and emissions load should portfolio operations prepare for?",
                "municipal building energy load, cost, and emissions",
                "weather, occupancy, tariff, and project-conditioned load forecasting",
                "energy demand above contracted and resilient capacity",
                "megawatt-hours",
                S.ASSET,
                (R.CLIMATE_HAZARD, R.OPERATING_CAPACITY, R.REAL_TIME_STATE),
                "Do not present forecast energy, cost, or emissions as metered performance.",
            ),
            axis(
                D.PRIORITIZE,
                "decarbonization-portfolio",
                "Prioritize municipal building decarbonization",
                "Which envelope, controls, heat-pump, solar, storage, and commissioning projects should be funded?",
                "municipal building decarbonization portfolio",
                "carbon, comfort, resilience, equity, cost, and lifecycle optimization",
                "remaining lifecycle greenhouse-gas emissions",
                "tonnes CO2e",
                S.ASSET,
                (R.ASSET_CONDITION, R.EQUITY_ATTRIBUTE, R.LEGAL_REGULATORY),
                "Do not report modeled energy, carbon, comfort, or cost savings as realized.",
            ),
            axis(
                D.SITE,
                "distributed-clean-energy",
                "Site solar, storage, charging, and thermal assets",
                "Where should distributed clean-energy assets improve emissions, resilience, and service value?",
                "municipal distributed clean-energy asset locations",
                "electrical, structural, parcel, load, resilience, and community-value siting",
                "critical load without feasible clean-energy resilience coverage",
                "kilowatt-hours per outage",
                S.FACILITY,
                (R.LAND_PARCEL, R.LEGAL_REGULATORY, R.ASSET_CONDITION, R.OPERATING_CAPACITY),
                "Do not call a screened site interconnected, structurally feasible, permitted, financed, or built.",
            ),
            axis(
                D.ALLOCATE,
                "energy-capital-capacity",
                "Allocate energy capital, incentives, and delivery capacity",
                "How should capital, incentives, engineering, procurement, and commissioning capacity be distributed?",
                "municipal energy capital and project delivery capacity",
                "carbon, resilience, readiness, and minimum-service allocation",
                "qualified emissions-reduction projects without assigned capacity",
                "project-tonnes CO2e",
                S.ASSET,
                (R.OPERATING_CAPACITY, R.ASSET_CONDITION, R.EQUITY_ATTRIBUTE),
                "Do not report allocated capital or staff as a contract, installation, commissioning, or saving.",
            ),
            axis(
                D.SCHEDULE,
                "decarbonization-projects",
                "Schedule building decarbonization and commissioning",
                "When should audits, design, procurement, shutdowns, installation, commissioning, and measurement occur?",
                "municipal building decarbonization project schedule",
                "dependency, occupancy, procurement, season, and workforce scheduling",
                "project-days beyond feasible emissions-reduction milestones",
                "project-days",
                S.ASSET,
                (R.SERVICE_SCHEDULE, R.OPERATING_CAPACITY, R.LEGAL_REGULATORY),
                "Do not call a scheduled project procured, installed, commissioned, or operational.",
            ),
            axis(
                D.STRESS_TEST,
                "building-grid-stress",
                "Stress-test municipal buildings under grid and climate stress",
                "Which electrification and resilience strategy preserves critical services under peak, outage, weather, and equipment failures?",
                "municipal building energy continuity under grid and climate stress",
                "load, weather, grid, equipment, storage, and backup-power simulation",
                "scenario-weighted critical-load service interruption",
                "kilowatt-hours unserved",
                S.NETWORK,
                (R.CLIMATE_HAZARD, R.ASSET_CONDITION, R.OPERATING_CAPACITY),
                "Do not present synthetic load, outage, or backup performance as observed events.",
            ),
            axis(
                D.EVALUATE,
                "retrofit-performance",
                "Evaluate municipal building retrofit performance",
                "Did phased retrofits reduce weather-normalized energy and emissions while preserving comfort and service?",
                "phased municipal building energy retrofit",
                "matched building difference-in-differences with meter panels",
                "change in weather- and occupancy-normalized energy use",
                "kilowatt-hours per square meter",
                S.ASSET,
                (R.ASSET_CONDITION, R.REAL_TIME_STATE, R.OPERATING_CAPACITY),
                "Do not infer causal carbon, cost, or comfort effects without stable meters, factors, occupancy, and comparisons.",
            ),
        ),
    ),
    matrix_family(
        family_id="infrastructure.capital-finance",
        suite=SUITE,
        title="Capital portfolio and municipal finance",
        description=(
            "Eight decisions for obligation diagnosis, fiscal forecasting, portfolio selection, reserve "
            "siting, funding allocation, delivery scheduling, fiscal stress, and financing evaluation."
        ),
        affected_system="municipal capital planning, debt, grants, reserves, procurement, and asset delivery",
        decision_owner="chief financial officer and capital planning director",
        common_source_roles=(R.FINANCIAL_COST, R.ASSET_INVENTORY, R.OPERATING_CAPACITY),
        common_assumptions=(
            "Budgets, obligations, appropriations, encumbrances, expenditures, schedules, and assets are reconciled.",
            "All fiscal scenarios separate nominal, real, committed, contingent, and modeled amounts.",
        ),
        transportability_risks=(
            "Accounting, tax authority, debt limits, grants, procurement, labor, and markets differ.",
            "Historical delivery and cost relationships may shift under inflation or policy change.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "capital-obligation-friction",
                "Diagnose capital obligations, backlog, and delivery friction",
                "Which assets and projects show reconciled condition need, cost growth, delay, funding gap, or delivery risk?",
                "capital obligation, backlog, and delivery risk",
                "asset-budget-contract-schedule reconciliation",
                "verified high-consequence unfunded or delayed obligations",
                "currency",
                S.ASSET,
                (R.ASSET_CONDITION, R.LEGAL_REGULATORY, R.REAL_TIME_STATE),
                "Do not call a request, estimate, or plan an audited liability, appropriation, or expenditure.",
            ),
            axis(
                D.FORECAST,
                "capital-fiscal-outlook",
                "Forecast capital cost, revenue, debt, and delivery capacity",
                "What range of costs, revenues, grants, debt service, cash flow, and completion should planning use?",
                "multi-year municipal capital and fiscal outlook",
                "scenario-based revenue, cost, cash-flow, and project-stage forecasting",
                "capital obligation above affordable deliverable capacity",
                "currency",
                S.CITYWIDE,
                (R.LEGAL_REGULATORY, R.REAL_TIME_STATE, R.ASSET_CONDITION),
                "Do not present a fiscal scenario as an audited forecast, rating opinion, or promised project completion.",
            ),
            axis(
                D.PRIORITIZE,
                "capital-investment-portfolio",
                "Prioritize the municipal capital investment portfolio",
                "Which renewal, resilience, service, compliance, and growth projects should enter the constrained plan?",
                "municipal capital investment portfolio",
                "risk, service, equity, lifecycle, dependency, and fiscal optimization",
                "expected risk-adjusted unmet capital-service need",
                "service-value units",
                S.ASSET,
                (R.ASSET_CONDITION, R.EQUITY_ATTRIBUTE, R.LEGAL_REGULATORY),
                "Do not call a selected project appropriated, financed, procured, constructed, or beneficial.",
            ),
            axis(
                D.SITE,
                "capital-reserve-assets",
                "Site strategic reserve and shared municipal assets",
                "Where should shared depots, reserves, equipment, and continuity assets reduce portfolio-wide risk?",
                "shared municipal reserve and continuity asset locations",
                "cross-department network, hazard, parcel, cost, and burden-aware siting",
                "critical municipal services beyond resilient reserve coverage",
                "service-units",
                S.FACILITY,
                (R.LAND_PARCEL, R.CLIMATE_HAZARD, R.TRANSPORT_NETWORK, R.EQUITY_ATTRIBUTE),
                "Do not call a screened site acquired, appropriated, permitted, or operational.",
            ),
            axis(
                D.ALLOCATE,
                "capital-funding",
                "Allocate capital funding and delivery capacity",
                "How should pay-as-you-go funds, debt, grants, reserves, and project staff be assigned?",
                "municipal capital funding and delivery capacity",
                "legal, fiscal, dependency, readiness, and minimum-service allocation",
                "priority capital need without assigned affordable capacity",
                "currency",
                S.ASSET,
                (R.LEGAL_REGULATORY, R.ASSET_CONDITION, R.EQUITY_ATTRIBUTE),
                "Do not report a modeled allocation as an appropriation, bond issuance, grant, or expenditure.",
            ),
            axis(
                D.SCHEDULE,
                "capital-delivery",
                "Schedule capital procurement and delivery",
                "When should design, permitting, procurement, utility coordination, construction, and commissioning occur?",
                "municipal capital project delivery schedule",
                "funding, dependency, permit, procurement, season, and workforce scheduling",
                "priority project-days beyond service and compliance milestones",
                "project-days",
                S.ASSET,
                (R.SERVICE_SCHEDULE, R.LEGAL_REGULATORY, R.REAL_TIME_STATE),
                "Do not call a project schedule authorized, contracted, under construction, or complete.",
            ),
            axis(
                D.STRESS_TEST,
                "fiscal-capital-shock",
                "Stress-test the capital plan under fiscal and delivery shocks",
                "Which portfolio remains affordable and service-protective under revenue, rate, cost, delay, failure, and disaster shocks?",
                "municipal capital plan under fiscal and delivery stress",
                "correlated fiscal, cost, schedule, asset, and hazard simulation",
                "scenario-weighted critical service and fiscal threshold breach",
                "breach-years",
                S.CITYWIDE,
                (R.CLIMATE_HAZARD, R.ASSET_CONDITION, R.LEGAL_REGULATORY),
                "Do not present synthetic fiscal paths as audited forecasts, ratings, defaults, or observed losses.",
            ),
            axis(
                D.EVALUATE,
                "delivery-reform-effect",
                "Evaluate capital delivery and financing reforms",
                "Did phased procurement, bundling, funding, or delivery reforms improve verified cost and schedule performance?",
                "phased municipal capital delivery and financing reform",
                "matched project cohort event-study with scope-change controls",
                "change in scope-adjusted cost and delivery variance",
                "percentage points",
                S.ASSET,
                (R.LEGAL_REGULATORY, R.REAL_TIME_STATE, R.ASSET_CONDITION),
                "Do not infer causal public value, quality, or fiscal health from cost and schedule variance alone.",
            ),
        ),
    ),
)

__all__ = ["INFRASTRUCTURE_FAMILIES"]
