"""Forty mobility, accessibility, and transport-operations decision designs."""

# ruff: noqa: E501 -- long policy statements are indivisible catalog content.

from civicdecision.deep.models import ApplicationSuite
from civicdecision.scenario_library.matrix import axis, matrix_family
from civicdecision.scenario_library.seeds import D, R, S

SUITE = ApplicationSuite.MOBILITY_ACCESS
BOUNDARY = (
    "Network, request, and schedule records do not establish individual travel behavior or harm.",
    "Optimized routes and allocations are planning outputs, not dispatched or completed trips.",
    "Design-only records do not claim current city data, implementation, compliance, or impact.",
)


MOBILITY_FAMILIES = (
    matrix_family(
        family_id="mobility.transit-reliability",
        suite=SUITE,
        title="Transit reliability and passenger continuity",
        description=(
            "Eight decisions covering reliability diagnosis, demand and delay forecasting, corridor "
            "investment, transfer siting, vehicle allocation, timetable design, disruption stress, "
            "and service-change evaluation."
        ),
        affected_system="fixed-route public transit service and passenger connections",
        decision_owner="transit chief operating officer and service-planning director",
        common_source_roles=(R.TRANSPORT_NETWORK, R.SERVICE_SCHEDULE, R.GEOGRAPHIC_IDENTITY),
        common_assumptions=(
            "Trips, stops, vehicle observations, disruptions, and calendars share a versioned service day.",
            "Passenger loads and transfer behavior are measured or represented as bounded assumptions.",
        ),
        transportability_risks=(
            "Fare policy, headways, fleet, labor rules, topology, and passenger behavior vary by operator.",
            "Reliability metrics may not transfer between schedule-based and frequency-based service.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "delay-propagation",
                "Diagnose transit delay propagation and missed connections",
                "Which route segments and transfer nodes repeatedly propagate delay into passenger connection failures?",
                "route-segment delay propagation and transfer failure",
                "vehicle-trajectory and timetable dependency diagnosis",
                "passenger-weighted missed connections",
                "connections",
                S.NETWORK,
                (R.REAL_TIME_STATE, R.OPERATING_CAPACITY),
                "Do not infer passenger experience from vehicle delay without validated load and transfer evidence.",
            ),
            axis(
                D.FORECAST,
                "crowding-delay-load",
                "Forecast transit crowding and delay load",
                "What route- and time-specific crowding and delay envelope should dispatch prepare for?",
                "route-time passenger crowding and delay load",
                "hierarchical passenger-load and travel-time forecasting",
                "passenger-minutes above crowding and delay thresholds",
                "passenger-minutes",
                S.CORRIDOR,
                (R.REAL_TIME_STATE, R.OPERATING_CAPACITY),
                "Do not present forecast passenger loads or delays as observed service outcomes.",
            ),
            axis(
                D.PRIORITIZE,
                "reliability-investments",
                "Prioritize transit reliability investments",
                "Which signal, lane, stop, fleet, and operations projects best reduce passenger delay within lifecycle budgets?",
                "transit reliability capital and operations portfolio",
                "passenger-weighted lifecycle project optimization",
                "expected passenger-hours of unreliable service",
                "passenger-hours per year",
                S.ASSET,
                (R.ASSET_INVENTORY, R.ASSET_CONDITION, R.FINANCIAL_COST),
                "Do not report modeled passenger delay reduction as a realized project benefit.",
            ),
            axis(
                D.SITE,
                "transfer-hubs",
                "Site accessible transfer and recovery hubs",
                "Where should timed-transfer, layover, charging, and passenger-recovery capacity be located?",
                "accessible transfer and operational recovery hubs",
                "network-constrained hub location with timetable dependencies",
                "passengers beyond a reliable accessible transfer",
                "passengers per day",
                S.FACILITY,
                (R.FACILITY_INVENTORY, R.LAND_PARCEL, R.LEGAL_REGULATORY),
                "Do not call a candidate hub accessible, permitted, or operationally feasible without verification.",
            ),
            axis(
                D.ALLOCATE,
                "fleet-spares",
                "Allocate fleet, operators, and recovery capacity",
                "How should vehicles, operators, and spare capacity be assigned across routes and depots?",
                "transit fleet, operator, and recovery capacity",
                "equity-constrained block and spare allocation",
                "passenger demand without scheduled reliable capacity",
                "passenger-trips",
                S.NETWORK,
                (R.OPERATING_CAPACITY, R.EQUITY_ATTRIBUTE, R.REAL_TIME_STATE),
                "Do not describe a vehicle and operator assignment as delivered service.",
            ),
            axis(
                D.SCHEDULE,
                "timetable-connections",
                "Schedule headways, recovery time, and timed connections",
                "How should trips and recovery time be scheduled to balance reliability, transfers, and operator rules?",
                "route timetable, recovery, and connection schedule",
                "multi-route timetable optimization with stochastic travel times",
                "passenger-weighted excess wait and missed-connection time",
                "passenger-minutes",
                S.NETWORK,
                (R.OPERATING_CAPACITY, R.REAL_TIME_STATE, R.LEGAL_REGULATORY),
                "Do not call an optimized timetable published, staffed, or operated.",
            ),
            axis(
                D.STRESS_TEST,
                "network-disruption",
                "Stress-test transit continuity under network disruption",
                "Which operating plan preserves essential access under vehicle, infrastructure, weather, and staffing failures?",
                "transit network disruption and continuity strategy",
                "correlated fleet-network-demand disruption simulation",
                "essential passenger-trips left without viable service",
                "passenger-trips",
                S.NETWORK,
                (R.ASSET_CONDITION, R.OPERATING_CAPACITY, R.CLIMATE_HAZARD),
                "Do not present synthetic failures as predicted disruptions or simulated access as completed trips.",
            ),
            axis(
                D.EVALUATE,
                "priority-lane-effect",
                "Evaluate transit priority and schedule redesign",
                "Did phased transit-priority and timetable changes improve reliable passenger travel without displacement?",
                "phased transit-priority and timetable intervention",
                "route-level event-study with comparable untreated corridors",
                "change in passenger-weighted reliable travel time",
                "minutes per passenger-trip",
                S.CORRIDOR,
                (R.REAL_TIME_STATE, R.EQUITY_ATTRIBUTE),
                "Do not infer causal passenger benefits from simple before-after vehicle speed.",
            ),
        ),
    ),
    matrix_family(
        family_id="mobility.pedestrian-safety",
        suite=SUITE,
        title="Pedestrian safety and universal accessibility",
        description=(
            "Eight decisions spanning barrier diagnosis, risk forecasting, treatment portfolios, "
            "crossing siting, inspection allocation, work scheduling, closure stress, and evaluation."
        ),
        affected_system="pedestrian right-of-way, crossings, sidewalks, and accessible routes",
        decision_owner="vision-zero director and accessibility compliance officer",
        common_source_roles=(R.TRANSPORT_NETWORK, R.ASSET_INVENTORY, R.GEOGRAPHIC_IDENTITY),
        common_assumptions=(
            "Crash, conflict, barrier, sidewalk, crossing, and demand data have explicit observation processes.",
            "Accessibility is evaluated across route continuity, slope, surface, crossing, and obstruction dimensions.",
        ),
        transportability_risks=(
            "Street design, enforcement, mobility-device needs, exposure, and reporting vary by place.",
            "Crash-only models underrepresent near misses and unreported accessibility barriers.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "accessible-route-breaks",
                "Diagnose pedestrian safety and accessible-route breaks",
                "Where do verified barriers, crossings, conflicts, speeds, and destinations break continuous safe access?",
                "continuous pedestrian safety and accessibility barriers",
                "route-level barrier and conflict topology diagnosis",
                "essential destinations without a continuous safe accessible route",
                "destinations",
                S.NETWORK,
                (R.ASSET_CONDITION, R.MUNICIPAL_DEMAND, R.EQUITY_ATTRIBUTE),
                "Do not equate request keywords or mapped sidewalks with verified accessible routes.",
                existing_template_ref="deep.mobility.accessibility-request.v1",
            ),
            axis(
                D.FORECAST,
                "pedestrian-conflict-risk",
                "Forecast pedestrian conflict and barrier demand",
                "What corridor-time risk envelope should guide temporary safety and inspection readiness?",
                "corridor-time pedestrian conflict and barrier demand",
                "exposure-conditioned conflict and service-demand forecasting",
                "high-risk pedestrian-hours without preventive coverage",
                "pedestrian-hours",
                S.CORRIDOR,
                (R.REAL_TIME_STATE, R.MUNICIPAL_DEMAND, R.ENVIRONMENTAL_EXPOSURE),
                "Do not call predicted conflicts crashes or infer exposure from population alone.",
            ),
            axis(
                D.PRIORITIZE,
                "safety-accessibility-treatments",
                "Prioritize pedestrian safety and accessibility treatments",
                "Which crossing, signal, curb-ramp, sidewalk, lighting, and speed treatments should be funded first?",
                "pedestrian safety and accessibility treatment portfolio",
                "exposure-, severity-, access-, and equity-weighted project optimization",
                "expected severe conflict and inaccessible-route burden",
                "risk-adjusted person-trips",
                S.ASSET,
                (R.ASSET_CONDITION, R.FINANCIAL_COST, R.EQUITY_ATTRIBUTE),
                "Do not present modeled risk reduction as prevented injuries.",
            ),
            axis(
                D.SITE,
                "safe-crossings",
                "Site safe crossings and accessible route connections",
                "Where should new crossings and route connections close verified network gaps?",
                "safe crossing and accessible-route connection locations",
                "pedestrian network gap location-allocation analysis",
                "high-demand crossings without a safe accessible connection",
                "crossings",
                S.CORRIDOR,
                (R.LAND_PARCEL, R.LEGAL_REGULATORY, R.EQUITY_ATTRIBUTE),
                "Do not call a screened crossing compliant or safe without engineering review.",
            ),
            axis(
                D.ALLOCATE,
                "inspection-quick-build",
                "Allocate inspections and quick-build safety resources",
                "How should inspectors, temporary barriers, signal crews, and accessibility repairs be distributed?",
                "pedestrian inspection and quick-build resources",
                "minimum-access and severity-constrained crew allocation",
                "verified high-consequence barriers without assigned response",
                "barriers",
                S.SERVICE_AREA,
                (R.OPERATING_CAPACITY, R.EQUITY_ATTRIBUTE, R.MUNICIPAL_DEMAND),
                "Do not report assigned crews as completed repairs or verified compliance.",
            ),
            axis(
                D.SCHEDULE,
                "right-of-way-work",
                "Schedule sidewalk, crossing, and signal work",
                "When should inspections and repairs occur to minimize access disruption and coordinate dependencies?",
                "pedestrian right-of-way inspection and repair schedule",
                "dependency-aware work-window scheduling",
                "high-consequence barrier-days awaiting verified completion",
                "barrier-days",
                S.ASSET,
                (R.ASSET_CONDITION, R.SERVICE_SCHEDULE, R.OPERATING_CAPACITY),
                "Do not infer repair completion from work-order closure alone.",
            ),
            axis(
                D.STRESS_TEST,
                "accessible-detours",
                "Stress-test accessible routes during closures and hazards",
                "Which detour and continuity plan preserves accessible essential trips during street, weather, or facility closures?",
                "accessible pedestrian continuity under closures",
                "mobility-profile network failure and detour simulation",
                "essential destinations unreachable by an accessible detour",
                "destinations",
                S.NETWORK,
                (R.CLIMATE_HAZARD, R.REAL_TIME_STATE, R.FACILITY_INVENTORY),
                "Do not describe simulated accessible detours as field-verified or universally usable.",
            ),
            axis(
                D.EVALUATE,
                "quick-build-safety-effect",
                "Evaluate quick-build pedestrian safety treatments",
                "Did phased quick-build treatments reduce measured conflicts and improve accessible crossing performance?",
                "phased quick-build pedestrian safety treatment",
                "matched corridor event-study with exposure measurement",
                "change in exposure-normalized severe pedestrian conflicts",
                "conflicts per thousand crossings",
                S.CORRIDOR,
                (R.ENVIRONMENTAL_EXPOSURE, R.EQUITY_ATTRIBUTE),
                "Do not infer injury prevention from unvalidated conflict detection or uncontrolled before-after counts.",
            ),
        ),
    ),
    matrix_family(
        family_id="mobility.freight-curb",
        suite=SUITE,
        title="Urban freight and curb operations",
        description=(
            "Eight decisions for curb diagnosis, demand forecasting, loading investment, hub siting, "
            "space allocation, reservation schedules, disruption stress, and policy evaluation."
        ),
        affected_system="commercial curb, loading, delivery, and urban freight network",
        decision_owner="curb-management director and city freight coordinator",
        common_source_roles=(R.TRANSPORT_NETWORK, R.GEOGRAPHIC_IDENTITY, R.REAL_TIME_STATE),
        common_assumptions=(
            "Curb regulations, occupancy, deliveries, violations, and travel effects have consistent timestamps and locations.",
            "Observed platform or sensor activity represents only its measured market and street coverage.",
        ),
        transportability_risks=(
            "Delivery markets, curb law, enforcement, land use, vehicle mix, and sensor coverage differ.",
            "Platform data may omit independent carriers and informal loading behavior.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "curb-friction",
                "Diagnose curb conflict and freight-access friction",
                "Where do regulations, occupancy, deliveries, double parking, safety, and access needs conflict?",
                "curb-segment freight and public-access conflicts",
                "time-resolved curb use and regulation reconciliation",
                "commercial stops without legal usable curb access",
                "stops",
                S.CORRIDOR,
                (R.LEGAL_REGULATORY, R.ASSET_INVENTORY, R.MUNICIPAL_DEMAND),
                "Do not infer all delivery behavior from citations, sensors, or one platform feed.",
            ),
            axis(
                D.FORECAST,
                "loading-demand",
                "Forecast loading demand and curb occupancy",
                "What block-time loading and occupancy range should dynamic curb operations prepare for?",
                "block-time freight loading demand and curb occupancy",
                "land-use and event-conditioned curb demand forecasting",
                "delivery-minutes without legal loading capacity",
                "vehicle-minutes",
                S.CORRIDOR,
                (R.LAND_PARCEL, R.SERVICE_SCHEDULE, R.OPERATING_CAPACITY),
                "Do not call forecast occupancy observed obstruction or illegal behavior.",
            ),
            axis(
                D.PRIORITIZE,
                "curb-conversion-portfolio",
                "Prioritize curb conversion and loading investments",
                "Which curb segments, loading technologies, and enforcement support should receive investment?",
                "curb conversion and freight-access investment portfolio",
                "multi-objective curb project prioritization",
                "freight delay and safety conflict burden",
                "risk-adjusted vehicle-hours",
                S.ASSET,
                (R.ASSET_INVENTORY, R.FINANCIAL_COST, R.EQUITY_ATTRIBUTE),
                "Do not describe modeled delay or conflict reductions as realized business benefits.",
            ),
            axis(
                D.SITE,
                "microhubs-loading-zones",
                "Site freight microhubs and loading zones",
                "Where should consolidation hubs and loading zones intercept demand without shifting burdens?",
                "urban freight microhub and loading-zone locations",
                "network and parcel-constrained consolidation siting",
                "freight demand beyond compliant loading or consolidation access",
                "deliveries per day",
                S.PARCEL,
                (R.LAND_PARCEL, R.LEGAL_REGULATORY, R.FINANCIAL_COST),
                "Do not label a screened microhub site viable without carrier, parcel, permitting, and community evidence.",
            ),
            axis(
                D.ALLOCATE,
                "curb-space",
                "Allocate curb space across freight and public uses",
                "How should finite curb frontage be divided among loading, access, transit, parking, and public space?",
                "time-specific curb frontage allocation",
                "multi-use equity and safety constrained curb allocation",
                "priority curb demand left unserved",
                "curb-meter-hours",
                S.CORRIDOR,
                (R.LEGAL_REGULATORY, R.EQUITY_ATTRIBUTE, R.COMMUNITY_INPUT),
                "Do not call an optimized curb allocation enacted regulation or public consensus.",
            ),
            axis(
                D.SCHEDULE,
                "loading-reservations",
                "Schedule loading reservations and curb regimes",
                "When should curb segments switch uses and reserve loading windows across the day?",
                "dynamic curb-use and loading-reservation schedule",
                "demand-responsive curb regime scheduling",
                "unserved priority loading and access time",
                "curb-minutes",
                S.CORRIDOR,
                (R.SERVICE_SCHEDULE, R.LEGAL_REGULATORY, R.OPERATING_CAPACITY),
                "Do not describe a generated reservation schedule as adopted, enforced, or used.",
            ),
            axis(
                D.STRESS_TEST,
                "freight-disruption",
                "Stress-test urban freight under curb and network disruption",
                "Which curb and consolidation strategy sustains essential deliveries during closures, surges, and fleet constraints?",
                "essential urban freight continuity under disruption",
                "delivery network, curb, and depot failure simulation",
                "essential deliveries outside feasible time windows",
                "deliveries",
                S.NETWORK,
                (R.OPERATING_CAPACITY, R.CLIMATE_HAZARD, R.FACILITY_INVENTORY),
                "Do not present synthetic delivery failures as forecasts or modeled completion as observed service.",
            ),
            axis(
                D.EVALUATE,
                "dynamic-curb-effect",
                "Evaluate dynamic curb management",
                "Did phased reservations or dynamic curb rules reduce verified conflict and delay without shifting harm?",
                "phased dynamic curb and loading reservation policy",
                "matched block-time policy evaluation with spillover zones",
                "change in legal loading success and conflict time",
                "percentage points",
                S.CORRIDOR,
                (R.LEGAL_REGULATORY, R.EQUITY_ATTRIBUTE),
                "Do not infer causal freight or safety effects without measuring enforcement, substitution, and spillovers.",
            ),
        ),
    ),
    matrix_family(
        family_id="mobility.emergency-mobility",
        suite=SUITE,
        title="Evacuation and emergency mobility",
        description=(
            "Eight decisions for mobility-needs diagnosis, clearance forecasting, network upgrades, "
            "pickup siting, vehicle allocation, evacuation schedules, failure stress, and exercise evaluation."
        ),
        affected_system="multimodal evacuation, assisted transport, and emergency access network",
        decision_owner="emergency transportation coordinator and incident commander",
        common_source_roles=(R.TRANSPORT_NETWORK, R.GEOGRAPHIC_IDENTITY, R.OPERATING_CAPACITY),
        common_assumptions=(
            "Evacuation demand, assistance eligibility, vehicle capacity, route state, and hazard timing are versioned.",
            "Compliance, household departure, and network degradation remain observed inputs or bounded scenarios.",
        ),
        transportability_risks=(
            "Hazards, vehicle ownership, disability access, road topology, trust, and compliance differ.",
            "Registration systems may undercount people needing assistance.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "evacuation-access-gaps",
                "Diagnose evacuation and assisted-mobility gaps",
                "Which populations and critical facilities lack a verified feasible evacuation or responder-access path?",
                "evacuation and emergency-access gaps",
                "hazard-aware multimodal accessibility and dependency diagnosis",
                "at-risk people without a verified feasible mobility plan",
                "people",
                S.NETWORK,
                (R.EQUITY_ATTRIBUTE, R.FACILITY_INVENTORY, R.CLIMATE_HAZARD),
                "Do not infer individual evacuation need or willingness from area demographics.",
            ),
            axis(
                D.FORECAST,
                "clearance-demand",
                "Forecast evacuation demand and clearance time",
                "What departure, assisted-transport, congestion, and clearance-time range follows the hazard envelope?",
                "hazard-specific evacuation demand and clearance time",
                "departure-choice and dynamic network forecasting",
                "people remaining in hazard areas after safe clearance time",
                "people",
                S.NETWORK,
                (R.CLIMATE_HAZARD, R.REAL_TIME_STATE, R.EQUITY_ATTRIBUTE),
                "Do not present behavioral assumptions or simulated clearance as actual evacuation.",
            ),
            axis(
                D.PRIORITIZE,
                "evacuation-readiness",
                "Prioritize emergency mobility readiness investments",
                "Which route, fleet, communication, power, and accessibility upgrades most improve safe clearance?",
                "emergency mobility readiness investment portfolio",
                "multi-hazard clearance and equity portfolio optimization",
                "expected people beyond safe clearance capacity",
                "people per event",
                S.ASSET,
                (R.ASSET_CONDITION, R.FINANCIAL_COST, R.EQUITY_ATTRIBUTE),
                "Do not call modeled clearance improvements saved lives or completed readiness work.",
            ),
            axis(
                D.SITE,
                "pickup-transfer-points",
                "Site accessible evacuation pickup and transfer points",
                "Where should pickup, medical transfer, and staging points operate outside hazard and access failures?",
                "accessible evacuation pickup and transfer locations",
                "multi-hazard capacitated pickup location-allocation",
                "assistance-eligible people beyond safe pickup access",
                "people",
                S.FACILITY,
                (R.FACILITY_INVENTORY, R.CLIMATE_HAZARD, R.EQUITY_ATTRIBUTE),
                "Do not label a candidate point safe or accessible without field and operations validation.",
            ),
            axis(
                D.ALLOCATE,
                "assisted-transport",
                "Allocate accessible vehicles and emergency mobility teams",
                "How should accessible vehicles, drivers, escorts, and medical transport slots be assigned?",
                "assisted evacuation vehicles and support teams",
                "priority- and time-window-constrained fleet allocation",
                "eligible evacuation needs without assigned transport",
                "person-trips",
                S.NETWORK,
                (R.EQUITY_ATTRIBUTE, R.REAL_TIME_STATE, R.SERVICE_SCHEDULE),
                "Do not report assigned transport as passenger contact, pickup, or safe arrival.",
            ),
            axis(
                D.SCHEDULE,
                "phased-evacuation",
                "Schedule phased multimodal evacuation",
                "When should zones, transit, assisted transport, control points, and responder routes activate?",
                "phased multimodal evacuation and responder-access schedule",
                "clearance-time scheduling with protected responder flows",
                "people uncleared when route safety thresholds are crossed",
                "people",
                S.NETWORK,
                (R.REAL_TIME_STATE, R.SERVICE_SCHEDULE, R.CLIMATE_HAZARD),
                "Do not call an optimized evacuation timetable an issued order or completed movement.",
                existing_template_ref="deep.mobility.real-time-reroute.v1",
            ),
            axis(
                D.STRESS_TEST,
                "evacuation-network-failure",
                "Stress-test evacuation under correlated network failure",
                "Which plan preserves clearance and responder access under blocked links, outages, fleet loss, and demand surge?",
                "evacuation continuity under correlated network failure",
                "dynamic multimodal network and fleet failure simulation",
                "scenario-weighted people beyond safe clearance",
                "people",
                S.NETWORK,
                (R.CLIMATE_HAZARD, R.REAL_TIME_STATE, R.ASSET_CONDITION),
                "Do not treat synthetic network failures or compliance assumptions as predicted events.",
            ),
            axis(
                D.EVALUATE,
                "evacuation-exercise-effect",
                "Evaluate emergency mobility exercises and outreach",
                "Did phased exercises and targeted outreach improve verified readiness and assisted-transport completion?",
                "phased evacuation exercise and preparedness outreach",
                "randomized encouragement and staggered exercise evaluation",
                "change in verified preparedness task completion",
                "percentage points",
                S.POPULATION_GROUP,
                (R.EQUITY_ATTRIBUTE, R.COMMUNITY_INPUT),
                "Do not infer real-disaster evacuation or survival effects from an exercise outcome.",
            ),
        ),
    ),
    matrix_family(
        family_id="mobility.active-mobility",
        suite=SUITE,
        title="Active mobility network and micromobility",
        description=(
            "Eight decisions for network-gap diagnosis, demand forecasting, project selection, station "
            "siting, fleet allocation, rebalancing schedules, network stress, and infrastructure evaluation."
        ),
        affected_system="walking, cycling, and shared micromobility network",
        decision_owner="active transportation director and shared-mobility program manager",
        common_source_roles=(R.TRANSPORT_NETWORK, R.GEOGRAPHIC_IDENTITY, R.ASSET_INVENTORY),
        common_assumptions=(
            "Trips, counts, facilities, stress levels, barriers, and shared-vehicle states use documented coverage.",
            "Observed shared-system trips do not represent all walking and cycling demand.",
        ),
        transportability_risks=(
            "Topography, climate, street stress, vehicle access, pricing, and safety perceptions vary.",
            "Platform data can exclude private bicycles, pedestrians, and non-users.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "low-stress-network-gaps",
                "Diagnose low-stress active-mobility network gaps",
                "Which missing links prevent continuous low-stress access between neighborhoods and essential destinations?",
                "continuous low-stress walking and cycling network gaps",
                "multimodal level-of-traffic-stress connectivity diagnosis",
                "essential trips disconnected from a low-stress network",
                "origin-destination pairs",
                S.NETWORK,
                (R.ASSET_CONDITION, R.EQUITY_ATTRIBUTE, R.MUNICIPAL_DEMAND),
                "Do not infer route accessibility or demand from request labels or mapped segments alone.",
            ),
            axis(
                D.FORECAST,
                "active-trip-demand",
                "Forecast active and shared-mobility demand",
                "What station, corridor, and time-specific trip and vehicle-availability range should operations prepare for?",
                "active and shared-mobility trip demand",
                "weather-event and land-use conditioned trip forecasting",
                "trip requests without feasible vehicle or route capacity",
                "trips",
                S.NETWORK,
                (R.REAL_TIME_STATE, R.LAND_PARCEL, R.CLIMATE_HAZARD),
                "Do not treat shared-platform demand as total walking or cycling demand.",
            ),
            axis(
                D.PRIORITIZE,
                "active-network-projects",
                "Prioritize active-mobility network projects",
                "Which protected links, crossings, greenways, and accessibility repairs close the most consequential gaps?",
                "active-mobility network project portfolio",
                "connectivity, safety, equity, and lifecycle project optimization",
                "essential trips remaining outside a low-stress accessible network",
                "origin-destination pairs",
                S.ASSET,
                (R.ASSET_CONDITION, R.FINANCIAL_COST, R.EQUITY_ATTRIBUTE),
                "Do not report modeled connectivity or safety gains as completed trips or prevented crashes.",
            ),
            axis(
                D.SITE,
                "shared-mobility-stations",
                "Site shared-mobility stations and secure parking",
                "Where should stations and secure parking expand access without obstructing pedestrian use?",
                "shared-mobility station and secure-parking locations",
                "demand-, access-, and right-of-way-constrained facility siting",
                "residents beyond reliable shared-mobility access",
                "people",
                S.FACILITY,
                (R.LAND_PARCEL, R.LEGAL_REGULATORY, R.EQUITY_ATTRIBUTE),
                "Do not label a candidate station feasible, accessible, or publicly accepted without validation.",
            ),
            axis(
                D.ALLOCATE,
                "shared-fleet",
                "Allocate shared bicycles, devices, and charging capacity",
                "How should vehicles, adaptive devices, docks, and charging capacity be distributed?",
                "shared-mobility fleet and charging capacity",
                "minimum-access and demand-responsive fleet allocation",
                "forecast trips without an available suitable vehicle",
                "trips",
                S.FACILITY,
                (R.REAL_TIME_STATE, R.OPERATING_CAPACITY, R.EQUITY_ATTRIBUTE),
                "Do not report vehicle allocation as availability at use time or completed equitable access.",
            ),
            axis(
                D.SCHEDULE,
                "fleet-rebalancing",
                "Schedule shared-mobility rebalancing and maintenance",
                "When should vehicles be rebalanced, charged, inspected, and returned to service?",
                "shared-mobility rebalancing and maintenance schedule",
                "forecast-driven routing and maintenance scheduling",
                "station-hours outside vehicle availability targets",
                "station-hours",
                S.NETWORK,
                (R.REAL_TIME_STATE, R.SERVICE_SCHEDULE, R.OPERATING_CAPACITY),
                "Do not call an optimized rebalancing route executed or a work order verified complete.",
            ),
            axis(
                D.STRESS_TEST,
                "active-network-continuity",
                "Stress-test active-mobility network continuity",
                "Which detours and operating plan preserve low-stress access during closures, weather, and fleet outages?",
                "active-mobility continuity under network and fleet disruption",
                "link-failure, weather, and fleet-availability simulation",
                "essential trips without a low-stress feasible alternative",
                "origin-destination pairs",
                S.NETWORK,
                (R.CLIMATE_HAZARD, R.REAL_TIME_STATE, R.ASSET_CONDITION),
                "Do not describe a modeled detour as field-verified safe or an assumed trip as observed.",
            ),
            axis(
                D.EVALUATE,
                "protected-network-effect",
                "Evaluate protected active-mobility network expansion",
                "Did phased protected links change exposure-normalized use, conflicts, and access across groups?",
                "phased protected walking and cycling network expansion",
                "corridor event-study with count and conflict panels",
                "change in low-stress trips and exposure-normalized conflicts",
                "trips and conflicts per day",
                S.CORRIDOR,
                (R.ENVIRONMENTAL_EXPOSURE, R.EQUITY_ATTRIBUTE),
                "Do not infer causal mode shift or injury reduction from selected counters or simple before-after totals.",
            ),
        ),
    ),
)

__all__ = ["MOBILITY_FAMILIES"]
