"""Thirty-two public-service operations decision designs."""

# ruff: noqa: E501 -- long policy statements are indivisible catalog content.

from civicdecision.deep.models import ApplicationSuite
from civicdecision.scenario_library.matrix import axis, matrix_family
from civicdecision.scenario_library.seeds import D, R, S

SUITE = ApplicationSuite.PUBLIC_SERVICE
BOUNDARY = (
    "Service requests measure reported workload, not verified incidents, need, harm, or resolution.",
    "Assignments and schedules are proposed operations, not completed work or public outcomes.",
    "Design records do not establish agency adoption, deployment, productivity, or resident impact.",
)


PUBLIC_SERVICE_FAMILIES = (
    matrix_family(
        family_id="public-service.demand",
        suite=SUITE,
        title="311 and public-service demand operations",
        description=(
            "Eight decisions for intake-pattern diagnosis, workload forecasting, service improvement, "
            "access siting, case allocation, staffing schedules, demand stress, and channel evaluation."
        ),
        affected_system="multichannel public-service intake, triage, dispatch, and resolution workflow",
        decision_owner="chief service officer and 311 operations director",
        common_source_roles=(R.MUNICIPAL_DEMAND, R.GEOGRAPHIC_IDENTITY, R.OPERATING_CAPACITY),
        common_assumptions=(
            "Requests, contacts, duplicates, service categories, assignments, work orders, and outcomes remain distinct.",
            "Channel and area comparisons account for taxonomy, access, publication, and reporting differences.",
        ),
        transportability_risks=(
            "Service taxonomies, channels, SLAs, agency ownership, reporting, and publication rules differ.",
            "Observed demand reflects both conditions and ability or willingness to report.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "request-workload",
                "Diagnose public-service request workload and workflow friction",
                "Which categories, channels, places, and handoffs produce persistent demand, duplication, delay, or rework?",
                "public-service request workload and workflow friction",
                "taxonomy-aware request-flow and handoff diagnosis",
                "requests with unresolved routing or repeated workflow transitions",
                "requests",
                S.SERVICE_AREA,
                (R.SERVICE_SCHEDULE, R.REAL_TIME_STATE),
                "Do not call requests verified incidents, unresolved harms, or failed service delivery.",
            ),
            axis(
                D.FORECAST,
                "service-workload",
                "Forecast multichannel public-service workload",
                "What category, channel, area, and time-specific demand range should service operations prepare for?",
                "multichannel public-service workload",
                "hierarchical category and arrival-process forecasting",
                "request workload above verified handling capacity",
                "requests per day",
                S.SERVICE_AREA,
                (R.SERVICE_SCHEDULE, R.REAL_TIME_STATE),
                "Do not present forecast requests as incidents, verified need, or service failures.",
            ),
            axis(
                D.PRIORITIZE,
                "service-improvement-portfolio",
                "Prioritize public-service workflow improvements",
                "Which intake, routing, self-service, field, translation, and quality improvements should be funded?",
                "public-service workflow improvement portfolio",
                "volume, burden, equity, failure-mode, and lifecycle prioritization",
                "expected avoidable request handling and resident effort",
                "case-hours",
                S.ASSET,
                (R.FINANCIAL_COST, R.EQUITY_ATTRIBUTE, R.COMMUNITY_INPUT),
                "Do not report modeled handling savings as realized productivity or resident satisfaction.",
                existing_template_ref="deep.public-service.total-demand.v1",
            ),
            axis(
                D.SITE,
                "service-access-points",
                "Site multilingual public-service access points",
                "Where should in-person, mobile, kiosk, and partner-assisted access fill verified channel gaps?",
                "multilingual public-service access locations",
                "channel-gap, travel, language, privacy, and capacity-aware siting",
                "residents beyond usable public-service access",
                "people",
                S.FACILITY,
                (R.FACILITY_INVENTORY, R.TRANSPORT_NETWORK, R.EQUITY_ATTRIBUTE),
                "Do not call a candidate access point usable, trusted, staffed, or accessible without user evidence.",
            ),
            axis(
                D.ALLOCATE,
                "case-routing-capacity",
                "Allocate service cases and response capacity",
                "How should cases, language support, supervisors, and field capacity be assigned across queues?",
                "public-service cases and response capacity",
                "skills-, urgency-, equity-, and SLA-constrained queue allocation",
                "priority requests without assigned qualified capacity",
                "requests",
                S.SERVICE_AREA,
                (R.SERVICE_SCHEDULE, R.REAL_TIME_STATE, R.EQUITY_ATTRIBUTE),
                "Do not report routed cases as contacted residents, completed work, or resolved outcomes.",
            ),
            axis(
                D.SCHEDULE,
                "seasonal-service-staffing",
                "Schedule seasonal public-service staffing",
                "When should channel, supervisor, specialist, and field capacity expand or shift with demand?",
                "seasonal public-service staffing and channel schedule",
                "forecast-driven skill and shift scheduling",
                "request-hours above qualified handling capacity",
                "request-hours",
                S.CITYWIDE,
                (R.SERVICE_SCHEDULE, R.REAL_TIME_STATE, R.LEGAL_REGULATORY),
                "Do not call a proposed staffing roster adopted, worked, productive, or sufficient.",
                existing_template_ref="deep.public-service.seasonal-staffing.v1",
            ),
            axis(
                D.STRESS_TEST,
                "service-demand-surge",
                "Stress-test public-service continuity under demand surge",
                "Which intake and field-response plan sustains priority services during event, outage, absence, and channel surges?",
                "public-service continuity under multichannel demand surge",
                "arrival, channel, workforce, system, and field-capacity simulation",
                "scenario-weighted priority requests beyond response targets",
                "requests",
                S.NETWORK,
                (R.ASSET_CONDITION, R.CLIMATE_HAZARD, R.REAL_TIME_STATE),
                "Do not present synthetic requests, failures, or response times as observed service performance.",
            ),
            axis(
                D.EVALUATE,
                "channel-redesign-effect",
                "Evaluate service intake and routing redesign",
                "Did phased channel and routing changes reduce verified resident effort and workflow delay without exclusion?",
                "phased public-service channel and routing redesign",
                "staggered queue or service-area evaluation with outcome panels",
                "change in verified end-to-end handling time and repeat contact",
                "hours and percentage points",
                S.SERVICE_AREA,
                (R.EQUITY_ATTRIBUTE, R.COMMUNITY_INPUT, R.SERVICE_SCHEDULE),
                "Do not infer resident welfare, satisfaction, or causal resolution from closure codes alone.",
            ),
        ),
    ),
    matrix_family(
        family_id="public-service.sanitation",
        suite=SUITE,
        title="Sanitation, waste, and street cleanliness",
        description=(
            "Eight decisions for sanitation signal diagnosis, workload forecasting, asset investment, "
            "facility siting, crew allocation, route scheduling, disruption stress, and intervention evaluation."
        ),
        affected_system="waste collection, recycling, street cleaning, illegal-dumping, and sanitation response",
        decision_owner="sanitation commissioner and waste operations chief",
        common_source_roles=(R.MUNICIPAL_DEMAND, R.ASSET_INVENTORY, R.TRANSPORT_NETWORK),
        common_assumptions=(
            "Requests, route events, tonnage, inspections, dumping evidence, contamination, and completion remain distinct.",
            "Waste generation and service demand are measured or modeled with declared coverage.",
        ),
        transportability_risks=(
            "Collection systems, housing form, waste law, contracts, markets, and reporting behavior differ.",
            "Request labels and tonnage do not fully capture cleanliness or illegal dumping.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "sanitation-workload",
                "Diagnose sanitation workload and recurring failure patterns",
                "Which routes, assets, categories, places, and handoffs show persistent sanitation workload or verified failure?",
                "sanitation request workload and recurring service patterns",
                "taxonomy, route, asset, and work-order reconciliation",
                "verified recurring sanitation tasks without durable resolution",
                "tasks",
                S.SERVICE_AREA,
                (R.ASSET_CONDITION, R.REAL_TIME_STATE),
                "Do not convert sanitation-related request keywords into verified waste conditions.",
            ),
            axis(
                D.FORECAST,
                "waste-service-demand",
                "Forecast waste, recycling, and cleaning workload",
                "What route-time volume, contamination, cleaning, and exception workload should operations prepare for?",
                "waste collection and street-cleaning workload",
                "seasonal route, land-use, and event-conditioned forecasting",
                "service workload above route and facility capacity",
                "tasks per day",
                S.NETWORK,
                (R.LAND_PARCEL, R.REAL_TIME_STATE, R.OPERATING_CAPACITY),
                "Do not present forecast workload as observed tonnage, dumping, contamination, or missed service.",
            ),
            axis(
                D.PRIORITIZE,
                "sanitation-improvements",
                "Prioritize sanitation assets and service improvements",
                "Which vehicles, containers, depots, public bins, route tools, and prevention measures should be funded?",
                "sanitation asset and service improvement portfolio",
                "failure, demand, equity, cost, and lifecycle portfolio optimization",
                "expected sanitation service failure and overflow burden",
                "service-hours",
                S.ASSET,
                (R.ASSET_CONDITION, R.FINANCIAL_COST, R.EQUITY_ATTRIBUTE),
                "Do not report modeled cleanliness or service gains as observed outcomes.",
                existing_template_ref="deep.public-service.sanitation-workload.v1",
            ),
            axis(
                D.SITE,
                "sanitation-facilities",
                "Site sanitation depots, public bins, and drop-off facilities",
                "Where should operations and public facilities improve access while limiting traffic and environmental burdens?",
                "sanitation depot, bin, and drop-off locations",
                "demand, network, parcel, environmental, and burden-aware siting",
                "service demand beyond feasible sanitation facility coverage",
                "tasks per day",
                S.FACILITY,
                (R.LAND_PARCEL, R.ENVIRONMENTAL_EXPOSURE, R.LEGAL_REGULATORY, R.EQUITY_ATTRIBUTE),
                "Do not call a screened sanitation site permitted, safe, accepted, or built.",
            ),
            axis(
                D.ALLOCATE,
                "sanitation-crews-fleet",
                "Allocate sanitation crews, fleet, and prevention capacity",
                "How should crews, vehicles, inspectors, containers, and outreach be distributed across service areas?",
                "sanitation crews, vehicles, and prevention resources",
                "minimum-service and risk-constrained operational allocation",
                "priority sanitation workload without assigned capacity",
                "tasks",
                S.NETWORK,
                (R.OPERATING_CAPACITY, R.REAL_TIME_STATE, R.EQUITY_ATTRIBUTE),
                "Do not report assigned crews or vehicles as completed collection, cleaning, or prevention.",
            ),
            axis(
                D.SCHEDULE,
                "collection-cleaning-routes",
                "Schedule collection, cleaning, inspection, and maintenance routes",
                "When should routes, inspections, container service, and fleet maintenance occur?",
                "sanitation collection, cleaning, and maintenance schedule",
                "demand-, network-, shift-, and facility-constrained routing",
                "priority service-hours outside collection and cleaning targets",
                "service-hours",
                S.NETWORK,
                (R.SERVICE_SCHEDULE, R.REAL_TIME_STATE, R.OPERATING_CAPACITY),
                "Do not call a generated route driven or a scheduled task verified complete.",
            ),
            axis(
                D.STRESS_TEST,
                "waste-continuity",
                "Stress-test sanitation continuity under compound disruption",
                "Which operating plan sustains essential collection during weather, fleet, facility, workforce, and market failures?",
                "sanitation continuity under compound operational disruption",
                "waste-flow, route, fleet, facility, workforce, and market simulation",
                "scenario-weighted essential collection left unserved",
                "ton-days",
                S.NETWORK,
                (R.CLIMATE_HAZARD, R.ASSET_CONDITION, R.FACILITY_INVENTORY),
                "Do not present synthetic waste, outages, or unserved routes as observed events.",
            ),
            axis(
                D.EVALUATE,
                "waste-prevention-effect",
                "Evaluate waste prevention and collection redesign",
                "Did phased route, container, enforcement, or outreach changes reduce verified overflow and contamination?",
                "phased sanitation service and waste-prevention redesign",
                "matched route or district event-study with spillover measurement",
                "change in verified overflow, contamination, and missed collection",
                "events per thousand stops",
                S.SERVICE_AREA,
                (R.ENVIRONMENTAL_EXPOSURE, R.EQUITY_ATTRIBUTE, R.COMMUNITY_INPUT),
                "Do not infer causal cleanliness, behavior, or environmental benefits from requests alone.",
            ),
        ),
    ),
    matrix_family(
        family_id="public-service.emergency-response",
        suite=SUITE,
        title="Emergency response readiness and allocation",
        description=(
            "Eight decisions for response-gap diagnosis, demand forecasting, readiness portfolios, "
            "station siting, unit allocation, coverage schedules, surge stress, and system evaluation."
        ),
        affected_system="non-clinical emergency call handling, unit readiness, and incident support network",
        decision_owner="emergency communications director and public-safety operations chief",
        common_source_roles=(R.MUNICIPAL_DEMAND, R.TRANSPORT_NETWORK, R.OPERATING_CAPACITY),
        common_assumptions=(
            "Calls, incidents, dispositions, unit states, travel, scene time, and outcomes remain distinct.",
            "Any operational recommendation requires agency safety review and cannot automate high-stakes dispatch.",
        ),
        transportability_risks=(
            "Call coding, dispatch policy, mutual aid, geography, traffic, staffing, and incident mix differ.",
            "Recorded response time may omit call processing, staging, or outcome quality.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "response-coverage-gaps",
                "Diagnose emergency response coverage and workflow gaps",
                "Which call-processing, dispatch, travel, handoff, and availability stages drive verified coverage gaps?",
                "emergency response workflow and coverage gaps",
                "stage-resolved call-to-unit process diagnosis",
                "priority incidents outside verified response targets",
                "incidents",
                S.SERVICE_AREA,
                (R.REAL_TIME_STATE, R.SERVICE_SCHEDULE, R.EQUITY_ATTRIBUTE),
                "Do not infer incident severity, fault, survival, or service quality from response time alone.",
            ),
            axis(
                D.FORECAST,
                "incident-unit-demand",
                "Forecast emergency call and unit demand",
                "What place-time priority call, unit-hour, and mutual-aid demand range should readiness planning use?",
                "emergency call and unit-hour demand",
                "spatiotemporal incident and service-time forecasting",
                "priority unit-hours above deployable capacity",
                "unit-hours",
                S.SERVICE_AREA,
                (R.REAL_TIME_STATE, R.SERVICE_SCHEDULE, R.CLIMATE_HAZARD),
                "Do not present forecast calls as incidents, casualties, or verified emergency need.",
            ),
            axis(
                D.PRIORITIZE,
                "response-readiness-portfolio",
                "Prioritize emergency response readiness investments",
                "Which communications, fleet, station, training, accessibility, and mutual-aid investments should be funded?",
                "emergency response readiness investment portfolio",
                "coverage, resilience, safety, equity, and lifecycle prioritization",
                "expected priority response-capacity shortfall",
                "unit-hours per year",
                S.ASSET,
                (R.ASSET_CONDITION, R.FINANCIAL_COST, R.EQUITY_ATTRIBUTE),
                "Do not report modeled response improvements as lives saved or delivered readiness.",
            ),
            axis(
                D.SITE,
                "response-bases",
                "Site emergency response and standby bases",
                "Where should fixed and temporary bases improve resilient time-dependent coverage?",
                "emergency response base and standby locations",
                "capacitated time-dependent coverage location-allocation",
                "priority demand beyond resilient response coverage",
                "incidents per day",
                S.FACILITY,
                (R.FACILITY_INVENTORY, R.LAND_PARCEL, R.REAL_TIME_STATE),
                "Do not call a screened base operational, safe, staffed, or guaranteed to meet response targets.",
            ),
            axis(
                D.ALLOCATE,
                "response-units",
                "Allocate emergency response units and standby capacity",
                "How should deployable units, specialist teams, supervisors, and mutual-aid reserves be positioned?",
                "emergency response units and standby capacity",
                "minimum-coverage and workload-balanced unit allocation",
                "priority demand without resilient unit coverage",
                "incident-equivalents",
                S.NETWORK,
                (R.REAL_TIME_STATE, R.SERVICE_SCHEDULE, R.EQUITY_ATTRIBUTE),
                "Do not present a planning allocation as an automated dispatch or completed response.",
            ),
            axis(
                D.SCHEDULE,
                "readiness-coverage",
                "Schedule emergency readiness and coverage",
                "When should shifts, standby posts, maintenance, training, and mutual-aid coverage operate?",
                "emergency response readiness and coverage schedule",
                "demand-, skill-, rest-, maintenance-, and coverage-constrained scheduling",
                "priority demand-hours below minimum deployable coverage",
                "demand-hours",
                S.NETWORK,
                (R.SERVICE_SCHEDULE, R.REAL_TIME_STATE, R.LEGAL_REGULATORY),
                "Do not call a proposed readiness roster staffed, safe, negotiated, or operated.",
            ),
            axis(
                D.STRESS_TEST,
                "multi-incident-surge",
                "Stress-test emergency response under correlated surge",
                "Which readiness strategy preserves priority coverage during concurrent incidents, outages, access loss, and staff absence?",
                "emergency response under correlated incident and capacity surge",
                "incident, service-time, network, facility, and workforce failure simulation",
                "scenario-weighted priority incidents without timely unit coverage",
                "incidents",
                S.NETWORK,
                (R.CLIMATE_HAZARD, R.ASSET_CONDITION, R.FACILITY_INVENTORY),
                "Do not present synthetic incidents, response times, or outcomes as forecasts or observed performance.",
            ),
            axis(
                D.EVALUATE,
                "dispatch-process-effect",
                "Evaluate emergency communications and deployment redesign",
                "Did phased call-processing or unit-positioning changes improve verified coverage without unequal service?",
                "phased emergency communications and deployment redesign",
                "staggered operational evaluation with incident-mix adjustment",
                "change in stage-resolved priority response time and coverage",
                "seconds and percentage points",
                S.SERVICE_AREA,
                (R.EQUITY_ATTRIBUTE, R.REAL_TIME_STATE, R.SERVICE_SCHEDULE),
                "Do not infer clinical, safety, or survival effects from response-time changes alone.",
            ),
        ),
    ),
    matrix_family(
        family_id="public-service.digital-access",
        suite=SUITE,
        title="Digital public access and administrative service delivery",
        description=(
            "Eight decisions for journey diagnosis, channel forecasting, service redesign, assisted-access "
            "siting, support allocation, appointment scheduling, outage stress, and digital-service evaluation."
        ),
        affected_system="public digital services, identity, applications, appointments, and assisted access",
        decision_owner="chief digital officer and administrative service delivery director",
        common_source_roles=(R.MUNICIPAL_DEMAND, R.SERVICE_SCHEDULE, R.DEMOGRAPHIC_CONTEXT),
        common_assumptions=(
            "Page events, applications, errors, appointments, contacts, decisions, and outcomes remain distinct.",
            "No automated score determines eligibility, enforcement, or denial without lawful human review.",
        ),
        transportability_risks=(
            "Eligibility, identity, language, disability access, connectivity, trust, and service design differ.",
            "Digital telemetry omits non-users and can encode device or tracking coverage.",
        ),
        claim_boundary=BOUNDARY,
        axes=(
            axis(
                D.DIAGNOSE,
                "service-journey-friction",
                "Diagnose digital and assisted-service journey friction",
                "Where do users encounter verified error, abandonment, repeat contact, language, access, or handoff friction?",
                "end-to-end public-service journey friction",
                "privacy-preserving event, application, appointment, and contact journey diagnosis",
                "eligible service journeys with unresolved verified friction",
                "journeys",
                S.POPULATION_GROUP,
                (R.EQUITY_ATTRIBUTE, R.COMMUNITY_INPUT, R.REAL_TIME_STATE),
                "Do not interpret non-completion as ineligibility, user error, disinterest, or lack of need.",
            ),
            axis(
                D.FORECAST,
                "channel-support-demand",
                "Forecast digital, phone, and in-person support demand",
                "What service, language, channel, device, and time-specific demand should support operations prepare for?",
                "multichannel administrative service and support demand",
                "service-event and journey-stage workload forecasting",
                "eligible journey demand above qualified channel capacity",
                "journeys per day",
                S.SERVICE_AREA,
                (R.OPERATING_CAPACITY, R.REAL_TIME_STATE, R.EQUITY_ATTRIBUTE),
                "Do not call forecast contacts eligible applicants, completed services, or verified unmet need.",
            ),
            axis(
                D.PRIORITIZE,
                "service-redesign-portfolio",
                "Prioritize accessible public-service redesign",
                "Which identity, form, language, accessibility, integration, support, and privacy improvements should be funded?",
                "accessible administrative service redesign portfolio",
                "journey-friction, equity, risk, privacy, and lifecycle prioritization",
                "verified user effort and preventable service failure",
                "journey-hours",
                S.ASSET,
                (R.FINANCIAL_COST, R.EQUITY_ATTRIBUTE, R.LEGAL_REGULATORY),
                "Do not report modeled time savings as realized uptake, eligibility, or resident welfare.",
            ),
            axis(
                D.SITE,
                "assisted-digital-access",
                "Site assisted digital and administrative access",
                "Where should private, accessible, multilingual assisted-service points close verified access gaps?",
                "assisted digital and administrative service locations",
                "access, privacy, language, connectivity, and capacity-aware siting",
                "eligible residents beyond usable assisted service access",
                "people",
                S.FACILITY,
                (R.FACILITY_INVENTORY, R.TRANSPORT_NETWORK, R.EQUITY_ATTRIBUTE),
                "Do not call a candidate site usable, private, accessible, trusted, connected, or staffed.",
            ),
            axis(
                D.ALLOCATE,
                "navigation-support",
                "Allocate navigation, language, and accessibility support",
                "How should navigators, interpreters, accessibility specialists, devices, and appointment capacity be assigned?",
                "administrative service navigation and access support",
                "minimum-access and journey-complexity allocation",
                "eligible complex journeys without qualified support",
                "journeys",
                S.POPULATION_GROUP,
                (R.OPERATING_CAPACITY, R.EQUITY_ATTRIBUTE, R.REAL_TIME_STATE),
                "Do not report assigned support as contact, completed application, eligibility, or benefit receipt.",
            ),
            axis(
                D.SCHEDULE,
                "appointments-support",
                "Schedule appointments and multichannel support",
                "When should appointments, callbacks, interpreters, specialists, and assisted access operate?",
                "administrative appointment and support schedule",
                "skill, language, channel, accessibility, and deadline-aware scheduling",
                "eligible journey-hours outside service targets",
                "journey-hours",
                S.SERVICE_AREA,
                (R.OPERATING_CAPACITY, R.REAL_TIME_STATE, R.EQUITY_ATTRIBUTE),
                "Do not call a scheduled appointment attended, completed, eligible, or successful.",
            ),
            axis(
                D.STRESS_TEST,
                "digital-service-continuity",
                "Stress-test public-service continuity during digital outage",
                "Which fallback strategy preserves lawful accessible service during identity, platform, network, vendor, and staffing failures?",
                "administrative service continuity under digital and operational failure",
                "journey, platform, identity, channel, vendor, and capacity failure simulation",
                "scenario-weighted eligible journeys without lawful service path",
                "journeys",
                S.NETWORK,
                (R.ASSET_CONDITION, R.FACILITY_INVENTORY, R.LEGAL_REGULATORY),
                "Do not present synthetic outages or modeled fallback completions as observed incidents.",
            ),
            axis(
                D.EVALUATE,
                "assisted-service-effect",
                "Evaluate assisted digital service redesign",
                "Did phased redesign reduce verified completion friction without excluding non-digital users?",
                "phased accessible digital and assisted-service redesign",
                "randomized encouragement or staggered service evaluation",
                "change in verified eligible journey completion and user effort",
                "percentage points and minutes",
                S.POPULATION_GROUP,
                (R.EQUITY_ATTRIBUTE, R.COMMUNITY_INPUT, R.LEGAL_REGULATORY),
                "Do not infer benefit receipt, well-being, or causal inclusion from page completion alone.",
            ),
        ),
    ),
)

__all__ = ["PUBLIC_SERVICE_FAMILIES"]
